modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-or-later"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="PIQ"
description='''
在 Minecraft 方块表面运行 SFC/SNES 游戏的独立街机模组。
不内置或分发任何商业 ROM。
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_min_version},22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="piq_fc_arcade"
type="required"
versionRange="[0.31.0-alpha.76.40,0.31.0-alpha.77)"
ordering="AFTER"
side="BOTH"
