// SPDX-License-Identifier: GPL-3.0-or-later
package cn.piq.sfcarcade.core;

import cn.piq.sfcarcade.core.wasm.WasmSfcCore;
import java.util.*;

/** Original 65816 program: reads all 12 serial bits on both ports and paints port-specific colors.
 * No copyrighted game code/assets. Generated bytes exist only in memory and QA, not the mod JAR. */
public final class SfcTwoPortInputProbe {
    private static final class Code {
        final List<Integer> bytes=new ArrayList<>();
        final Map<String,Integer> labels=new HashMap<>();
        final Map<Integer,String> branches=new LinkedHashMap<>();
        void b(int... values){for(int v:values)bytes.add(v&255);}
        void label(String label){labels.put(label,bytes.size());}
        void branch(int opcode,String label){b(opcode,0);branches.put(bytes.size()-1,label);}
        byte[] finish(){
            for(var fix:branches.entrySet()){
                int d=labels.get(fix.getValue())-fix.getKey()-1;
                if(d < -128 || d > 127)throw new AssertionError("Branch out of range");
                bytes.set(fix.getKey(),d&255);
            }
            byte[] result=new byte[bytes.size()];
            for(int i=0;i<result.length;i++)result[i]=(byte)(int)bytes.get(i);
            return result;
        }
    }
    public static byte[] rom(){
        byte[] rom=SfcLegalTestRom.create();
        Code c=new Code();
        c.b(0x78,0x18,0xFB,0xC2,0x30,0xA2,0xFF,0x1F,0x9A,0xA9,0,0,0xE2,0x20);
        c.b(0xA9,0x80,0x8D,0,0x21,0x9C,0,0x42,0x9C,0x21,0x21,0x9C,0x22,0x21,0x9C,0x22,0x21);
        c.b(0xA9,0x0F,0x8D,0,0x21);
        c.label("vblankEnd");c.b(0xAD,0x12,0x42,0x29,0x80);c.branch(0xD0,"vblankEnd");
        c.label("vblankStart");c.b(0xAD,0x12,0x42,0x29,0x80);c.branch(0xF0,"vblankStart");
        c.b(0xA9,1,0x8D,0x16,0x40,0x9C,0x16,0x40,0x64,0,0xA2,12,0);
        c.label("serial");
        c.b(0xAD,0x16,0x40,0x29,1,0x05,0,0x85,0);
        c.b(0xAD,0x17,0x40,0x29,1,0x0A,0x05,0,0x85,0,0xCA);c.branch(0xD0,"serial");
        c.b(0x9C,0x21,0x21,0xA5,0,0x29,1);c.branch(0xF0,"noRed");
        c.b(0xA9,0x1F);c.branch(0x80,"redDone");
        c.label("noRed");c.b(0xA9,0);
        c.label("redDone");c.b(0x85,1,0xA5,0,0x29,2);c.branch(0xF0,"noGreen");
        c.b(0xA5,1,0x09,0xE0,0x85,1,0xA9,3,0x85,2);c.branch(0x80,"writeColor");
        c.label("noGreen");c.b(0x64,2);
        c.label("writeColor");c.b(0xA5,1,0x8D,0x22,0x21,0xA5,2,0x8D,0x22,0x21);
        int loop=0x8000+c.labels.get("vblankEnd");c.b(0x4C,loop&255,loop>>>8);
        byte[] p=c.finish();Arrays.fill(rom,0,512,(byte)0xFF);System.arraycopy(p,0,rom,0,p.length);
        // Recompute original homebrew's checksum after replacing its test program.
        int sum=0;for(int i=0;i<rom.length;i++)if(i<0x7FDC||i>0x7FDF)sum=(sum+Byte.toUnsignedInt(rom[i]))&65535;
        int checksum=(sum+0x1FE)&65535,complement=checksum^65535;
        rom[0x7FDC]=(byte)complement;rom[0x7FDD]=(byte)(complement>>>8);
        rom[0x7FDE]=(byte)checksum;rom[0x7FDF]=(byte)(checksum>>>8);
        return rom;
    }
    public static void main(String[] args) throws Exception {
        int cases=0,frames=0;
        try(SfcCore core=new WasmSfcCore()){
            core.loadRom(SfcRomImage.fromBytes(rom()));
            for(int port=-1;port<2;port++){
                for(int bit=0;bit<(port<0?1:12);bit++){
                    int p1=port==0?1<<bit:0,p2=port==1?1<<bit:0;
                    SfcFrameResult result=null;
                    for(int f=0;f<3;f++){result=core.runFrame(new SfcControllerState(p1),new SfcControllerState(p2));frames++;}
                    byte[] rgba=new byte[result.videoMode().requiredRgbaBytes()];core.copyRgbaFrame(rgba);
                    int matching=0;
                    for(int i=0;i<rgba.length;i+=4){
                        int r=Byte.toUnsignedInt(rgba[i]),g=Byte.toUnsignedInt(rgba[i+1]),b=Byte.toUnsignedInt(rgba[i+2]);
                        if(port<0?r<10&&g<10&&b<10:port==0?r>200&&g<20&&b<20:g>200&&r<20&&b<20)matching++;
                    }
                    if(matching<rgba.length/8)throw new AssertionError("Actual joypad effect wrong: port="+port+" bit="+bit+" matching="+matching);
                    cases++;
                }
            }
        }
        System.out.println("{\"ok\":true,\"input_effect_cases\":"+cases+",\"frames\":"+frames+",\"all_12_keys_both_ports\":true}");
    }
}
