[package]
name = "piq_nes_zapper_ffi"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[workspace]

[dependencies]
nes_rust = { path = "../nes-rust", features = ["zapper"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
