package cn.piq.fcarcade.home;
import cn.piq.fcarcade.session.*;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class HomeRuntimeAuthorityTest {
    final UUID host=UUID.randomUUID(),guest=UUID.randomUUID();final Object h=new Object(),g=new Object();
    HomeRuntimeAuthority<Object> runtime(){return new HomeRuntimeAuthority<>(host,h);}
    @Test void poweredHostStartsWithZeroControllerSockets(){var r=runtime();assertTrue(r.running());assertTrue(r.host(host,h));assertNull(r.player(host));assertNull(r.port(0));assertNull(r.port(1));}
    @Test void hostIdentityAloneNeverAuthorizesInput(){var r=runtime();assertFalse(r.authorized(host,h,UUID.randomUUID(),0));assertFalse(r.host(host,new Object()));assertFalse(r.host(guest,h));}
    @Test void hostMayBorrowSecondWithoutCreatingFirst(){var r=runtime();var lease=UUID.randomUUID();assertTrue(r.take(host,h,lease,1));assertNull(r.port(0));assertTrue(r.authorized(host,h,lease,1));assertFalse(r.authorized(host,h,lease,0));}
    @Test void onlyOnePhysicalSocketPerPlayer(){var r=runtime();assertTrue(r.take(host,h,UUID.randomUUID(),0));assertFalse(r.take(host,h,UUID.randomUUID(),1));}
    @Test void occupiedSocketCannotBeStolen(){var r=runtime();var lease=UUID.randomUUID();assertTrue(r.take(host,h,lease,0));assertFalse(r.take(guest,g,UUID.randomUUID(),0));assertEquals(lease,r.port(0).lease());}
    @Test void returningFirstDoesNotPromoteSecondOrStopHost(){var r=runtime();var a=UUID.randomUUID();var b=UUID.randomUUID();r.take(host,h,a,0);r.take(guest,g,b,1);assertEquals(0,r.release(host,h).port());assertTrue(r.running());assertTrue(r.host(host,h));assertNull(r.port(0));assertTrue(r.authorized(guest,g,b,1));}
    @Test void returningSecondDoesNotTouchFirst(){var r=runtime();var a=UUID.randomUUID();r.take(host,h,a,0);r.take(guest,g,UUID.randomUUID(),1);r.release(guest,g);assertTrue(r.authorized(host,h,a,0));assertNull(r.port(1));}
    @Test void emptySocketsKeepClockRunning(){var r=runtime();var clock=new LockstepState();clock.restart();for(int i=0;i<120;i++){var frame=clock.advanceFrame();assertEquals(0,frame.playerOneMask());assertEquals(0,frame.playerTwoMask());assertEquals(ZapperInput.NEUTRAL,frame.zapperState());}assertTrue(r.running());assertEquals(120,clock.targetFrame());}
    @Test void oldLoanCannotDriveOrReleaseReplacement(){var r=runtime();var old=UUID.randomUUID();var fresh=UUID.randomUUID();r.take(host,h,old,0);r.release(host,h);r.take(host,h,fresh,0);assertFalse(r.authorized(host,h,old,0));assertTrue(r.authorized(host,h,fresh,0));assertNull(r.release(host,new Object()));assertTrue(r.authorized(host,h,fresh,0));}
    @Test void connectionIdentityNotEqualsDefinesLoan(){var r=new HomeRuntimeAuthority<String>(host,new String("c"));String original=new String("guest");var lease=UUID.randomUUID();r.take(guest,original,lease,1);assertFalse(r.authorized(guest,new String("guest"),lease,1));assertNull(r.release(guest,new String("guest")));assertNotNull(r.port(1));}
    @Test void serverCapturedStaleSourceCanReclaimSocketWithoutGrantingReconnectAuthority(){var r=runtime();var first=UUID.randomUUID();var second=UUID.randomUUID();Object replacement=new Object();r.take(host,h,first,0);r.take(guest,g,second,1);assertFalse(r.authorized(guest,replacement,second,1));var stale=r.player(guest);assertNotNull(r.release(guest,stale.connection()));assertTrue(r.authorized(host,h,first,0));assertTrue(r.running());assertTrue(r.take(guest,replacement,UUID.randomUUID(),1));assertNull(r.release(guest,g));assertSame(replacement,r.player(guest).connection());}
    @Test void resetKeepsSocketsButAdvancesRevisionAndRejectsOldFrameInput(){var r=runtime();var lease=UUID.randomUUID();r.take(host,h,lease,0);long previous=r.revision();var clock=new LockstepState();clock.restart();assertTrue(clock.acceptInput(host,1,0,1,255));clock.restart();r.reset();assertTrue(r.revision()>previous);assertTrue(r.authorized(host,h,lease,0));assertFalse(clock.acceptInput(host,1,0,2,255));assertEquals(0,clock.advanceFrame().playerOneMask());}
    @Test void releaseClearsOnlyDepartingPortIncludingQueuedTap(){var r=runtime();r.take(host,h,UUID.randomUUID(),0);r.take(guest,g,UUID.randomUUID(),1);var clock=new LockstepState();clock.restart();clock.acceptInput(host,1,0,1,1);clock.acceptInput(host,1,0,2,0);clock.acceptInput(guest,1,1,1,2);var removed=r.release(host,h);clock.clearController(removed.port());clock.forgetPlayer(host);var f=clock.advanceFrame();assertEquals(0,f.playerOneMask());assertEquals(2,f.playerTwoMask());assertTrue(r.running());}
    @Test void closeInvalidatesHostAndAllSockets(){var r=runtime();var lease=UUID.randomUUID();r.take(host,h,lease,0);r.close();assertFalse(r.running());assertFalse(r.host(host,h));assertFalse(r.authorized(host,h,lease,0));assertFalse(r.take(guest,g,UUID.randomUUID(),1));}
    @Test void invalidPortsAndNullTokensNeverMutate(){var r=runtime();long rev=r.revision();assertFalse(r.take(host,h,null,0));assertFalse(r.take(host,h,UUID.randomUUID(),-1));assertFalse(r.take(host,h,UUID.randomUUID(),2));assertEquals(rev,r.revision());}
    @Test void fixedRosterPreservesP2WhileLegacyRosterStillPromotes(){var fixed=new SessionRoster();assertTrue(fixed.joinAt(host,0));assertTrue(fixed.joinAt(guest,1));fixed.removeFixed(host);assertEquals(ArcadeRole.PLAYER_TWO,fixed.roleOf(guest));var old=new SessionRoster();old.join(host);old.join(guest);old.remove(host);assertEquals(ArcadeRole.PLAYER_ONE,old.roleOf(guest));}
    @Test void revisionsChangeOnlyForCommittedState(){var r=runtime();long start=r.revision();var lease=UUID.randomUUID();assertTrue(r.take(host,h,lease,0));assertEquals(start+1,r.revision());assertFalse(r.take(guest,g,UUID.randomUUID(),0));assertEquals(start+1,r.revision());assertNull(r.release(guest,g));assertEquals(start+1,r.revision());r.release(host,h);assertEquals(start+2,r.revision());}
}
