package cn.piq.fcarcade.home;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class HomeIdleController29Test {
    final UUID player=UUID.randomUUID(),other=UUID.randomUUID();
    final HomeControllerLedger.Console console=new HomeControllerLedger.Console(UUID.randomUUID(),"minecraft:overworld",0,64,0);
    @Test void idleObjectHasNoSessionOrInputAuthority(){var l=new HomeControllerLedger();var p=l.borrow(console,0,player);assertNotNull(p);assertEquals(0,p.session());assertEquals(HomeControllerLedger.Phase.IDLE,p.phase());assertFalse(l.authorized(p.id(),player,console,0,0));assertFalse(l.authorized(p.id(),player,console,1,0));assertTrue(HomeControllerInventory.keepForPlayer(p,player,999999));}
    @Test void idleReservationCannotBeClonedByNewSession(){var l=new HomeControllerLedger();var p=l.borrow(console,0,player);assertNull(l.borrow(console,0,other));assertNull(l.issue(console,20,0,other));assertNotNull(l.issue(console,20,1,other));assertEquals(p,l.socket(console,0));}
    @Test void idleReservationCannotUseTwoPlayersOrPorts(){var l=new HomeControllerLedger();var p=l.borrow(console,0,player);assertNull(l.borrow(console,1,player));assertFalse(l.activate(p.id(),other,console,1,0));assertFalse(l.activate(p.id(),player,console,1,1));assertFalse(l.activate(p.id(),player,console,0,0));}
    @Test void approvePromotesExactObjectWithoutReplacingToken(){var l=new HomeControllerLedger();var p=l.borrow(console,0,player);assertTrue(l.activate(p.id(),player,console,12,0));assertEquals(p.id(),l.player(player).id());assertTrue(l.authorized(p.id(),player,console,12,0));assertFalse(l.authorized(p.id(),player,console,0,0));assertFalse(l.activate(p.id(),player,console,13,0));}
    @Test void powerOffPreservesObjectButRejectsOldSession(){var l=new HomeControllerLedger();var p=l.issue(console,12,0,player);var idle=l.idle(p.id());assertEquals(p.id(),idle.id());assertEquals(0,idle.session());assertFalse(l.authorized(p.id(),player,console,12,0));assertTrue(HomeControllerInventory.keepForPlayer(idle,player,99999));assertTrue(l.activate(p.id(),player,console,13,0));assertFalse(l.authorized(p.id(),player,console,12,0));assertTrue(l.authorized(p.id(),player,console,13,0));}
    @Test void physicalReturnRemovesOnlyChosenSocket(){var l=new HomeControllerLedger();var p=l.borrow(console,0,player);var q=l.borrow(console,1,other);l.revoke(p.id());assertNull(l.socket(console,0));assertEquals(q,l.socket(console,1));}
    @Test void idleTransferRotatesReceiptWithoutGrantingInput(){var l=new HomeControllerLedger();var p=l.borrow(console,1,player);var carrier=UUID.randomUUID();assertNotNull(l.toss(p.id(),player,carrier,120));var q=l.pickup(p.id(),carrier,other,120);assertNotEquals(p.id(),q.id());assertNull(l.get(p.id()));assertEquals(HomeControllerLedger.Phase.IDLE,q.phase());assertFalse(l.authorized(q.id(),other,console,0,1));assertTrue(HomeControllerInventory.keepForPlayer(q,other,99999));}
    @Test void idleReceiptCannotControlReplacementMachineAtSamePosition(){var l=new HomeControllerLedger();var p=l.borrow(console,0,player);var newMachine=new HomeControllerLedger.Console(UUID.randomUUID(),console.dimension(),0,64,0);assertFalse(l.activate(p.id(),player,newMachine,1,0));assertTrue(l.activate(p.id(),player,console,1,0));}
    @Test void idlingOnePlayerCannotEraseOtherActivePort(){var l=new HomeControllerLedger();var p=l.issue(console,1,0,player);var q=l.issue(console,1,1,other);l.idle(p.id());assertTrue(l.authorized(q.id(),other,console,1,1));assertFalse(l.authorized(p.id(),player,console,1,0));}
}
