package cn.piq.fcarcade.home;

import cn.piq.fcarcade.session.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HomeGunController29Test {
    final UUID host=UUID.randomUUID(),guest=UUID.randomUUID(),pad=UUID.randomUUID(),gun=UUID.randomUUID();final Object h=new Object(),g=new Object();
    HomeRuntimeAuthority<Object> runtime(){return new HomeRuntimeAuthority<>(host,h,true);}
    @Test void connectedGunModeDoesNotClaimP1OrAnySocket(){var r=runtime();assertTrue(r.gunMode());assertNull(r.port(0));assertNull(r.port(1));assertTrue(r.take(host,h,pad,0));assertTrue(r.running());}
    @Test void ordinaryP2CannotReplacePhysicalPortTwoGun(){var r=runtime();assertFalse(r.take(host,h,pad,1));assertTrue(r.takeGun(guest,g,gun));assertFalse(r.take(host,h,pad,1));assertTrue(r.authorized(guest,g,gun,1));}
    @Test void ordinaryModeStillHasTwoPadsAndCannotAcquireGun(){var r=new HomeRuntimeAuthority<>(host,h);assertTrue(r.take(host,h,pad,0));assertTrue(r.take(guest,g,gun,1));assertFalse(r.takeGun(host,h,UUID.randomUUID()));}
    @Test void samePersonCanTakePadThenGunAndPrimaryRoleIsP1(){var r=runtime();assertTrue(r.take(host,h,pad,0));assertTrue(r.takeGun(host,h,gun));assertEquals(2,r.controls(host).size());assertEquals(0,r.player(host).port());assertTrue(r.authorized(host,h,gun,1));assertTrue(r.authorized(host,h,pad,0));}
    @Test void samePersonCanTakeGunThenPadWithoutResettingHost(){var r=runtime();assertTrue(r.takeGun(host,h,gun));assertEquals(1,r.player(host).port());assertTrue(r.take(host,h,pad,0));assertEquals(0,r.player(host).port());assertTrue(r.host(host,h));}
    @Test void crossConnectionCannotAttachSecondDeviceToSamePlayer(){var r=runtime();assertTrue(r.take(host,h,pad,0));assertFalse(r.takeGun(host,new Object(),gun));assertNull(r.port(1));}
    @Test void returningPadKeepsGunAndDoesNotPromoteOrStop(){var r=runtime();r.take(host,h,pad,0);r.takeGun(host,h,gun);assertNotNull(r.release(host,h,pad,0));assertNull(r.port(0));assertEquals(1,r.player(host).port());assertTrue(r.authorized(host,h,gun,1));assertTrue(r.running());}
    @Test void returningGunKeepsPadAndHost(){var r=runtime();r.take(host,h,pad,0);r.takeGun(host,h,gun);assertNotNull(r.release(host,h,gun,1));assertTrue(r.authorized(host,h,pad,0));assertNull(r.port(1));assertTrue(r.running());}
    @Test void oldDeviceReturnCannotReleaseReplacementOrOtherPort(){var r=runtime();r.take(host,h,pad,0);r.takeGun(host,h,gun);r.release(host,h,gun,1);var fresh=UUID.randomUUID();r.takeGun(host,h,fresh);assertNull(r.release(host,h,gun,1));assertNull(r.release(host,h,gun,0));assertTrue(r.authorized(host,h,pad,0));assertTrue(r.authorized(host,h,fresh,1));}
    @Test void padAndGunSequenceWindowsRemainIndependentOnReturn(){var r=runtime();r.take(host,h,pad,0);r.takeGun(host,h,gun);var clock=new LockstepState();clock.restart();assertTrue(clock.acceptInput(pad,1,0,70,1));assertTrue(clock.acceptZapper(gun,1,80,ZapperInput.pack(12,13,false,true),false,false));r.release(host,h,pad,0);clock.clearController(0);clock.forgetPlayer(pad);assertFalse(clock.acceptZapper(gun,1,79,ZapperInput.NEUTRAL,true,false));var f=clock.advanceFrame();assertEquals(0,f.playerOneMask());assertTrue(ZapperInput.trigger(f.zapperState()));assertTrue(r.authorized(host,h,gun,1));}
    @Test void gunReturnCannotClearOtherPlayersPadQueue(){var r=runtime();r.take(host,h,pad,0);r.takeGun(guest,g,gun);var clock=new LockstepState();clock.restart();clock.acceptInput(pad,1,0,1,1);clock.acceptInput(pad,1,0,2,0);clock.acceptZapper(gun,1,1,ZapperInput.pack(12,13,false,true),false,false);r.release(guest,g,gun,1);clock.clearController(1);clock.clearZapper();clock.forgetPlayer(gun);assertEquals(1,clock.advanceFrame().playerOneMask());assertEquals(0,clock.advanceFrame().playerOneMask());assertTrue(r.authorized(host,h,pad,0));}
    @Test void sixBlockBoundaryIsInclusiveAndRejectsInvalidDistances(){assertTrue(HomeRuntimeAuthority.controllerInRange(0));assertTrue(HomeRuntimeAuthority.controllerInRange(36));assertTrue(HomeRuntimeAuthority.controllerInRange(Math.nextDown(36.0)));assertFalse(HomeRuntimeAuthority.controllerInRange(Math.nextUp(36.0)));assertFalse(HomeRuntimeAuthority.controllerInRange(49));assertFalse(HomeRuntimeAuthority.controllerInRange(Double.NaN));assertFalse(HomeRuntimeAuthority.controllerInRange(Double.POSITIVE_INFINITY));assertFalse(HomeRuntimeAuthority.controllerInRange(-1));}
    @Test void leavingOneSixBlockCableCannotCloseRuntimeOrOtherDevice(){var r=runtime();r.take(host,h,pad,0);r.takeGun(guest,g,gun);if(!HomeRuntimeAuthority.controllerInRange(36.0001))r.release(host,h,pad,0);assertTrue(r.running());assertTrue(r.host(host,h));assertTrue(r.authorized(guest,g,gun,1));}
    @Test void resetKeepsBothExactDevicesButOldEpochCannotAffectEither(){var r=runtime();r.take(host,h,pad,0);r.takeGun(host,h,gun);var clock=new LockstepState();clock.restart();clock.restart();r.reset();assertTrue(r.authorized(host,h,pad,0));assertTrue(r.authorized(host,h,gun,1));assertFalse(clock.acceptInput(pad,1,0,1,255));assertFalse(clock.acceptZapper(gun,1,1,ZapperInput.pack(1,1,false,true),false,false));var f=clock.advanceFrame();assertEquals(0,f.playerOneMask());assertEquals(ZapperInput.NEUTRAL,f.zapperState());}
}
