package cn.piq.sfchome.server;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
/** Wiring contracts supplement, not replace, pure transaction and actual frozen-core tests. */
class SfcJoinSourceTest {
    String source(String n)throws Exception{return Files.readString(Path.of("src/main/java/cn/piq/sfchome/"+n+".java"));}
    @Test void approvalOnlyAllocatesCandidateAndAtomicCommitPublishesPort()throws Exception{String s=source("server/SfcHomeServer");String approval=s.substring(s.indexOf("public static void decideJoin"),s.indexOf("private static void joinReady"));assertTrue(approval.contains("j.gate.approve"));assertTrue(approval.contains("j.second=grant"));assertFalse(approval.contains("s.ports[j.port]="));String commit=s.substring(s.indexOf("public static void joinApplied"),s.indexOf("private static void abortJoin"));assertTrue(commit.indexOf("j.gate.commit")<commit.indexOf("s.ports[j.port]=j.second"));assertTrue(s.contains("if(lease==null||!lease.player.equals(p.getUUID())||!endpointFacts(p,lease,s.connection))return"));}
    @Test void wholeIdentityAndPermissionChainRechecked()throws Exception{String s=source("server/SfcHomeServer");for(String expected:new String[]{"!s.host.id.equals(j.gate.hostLease)","!s.connection.consoleId().equals(j.gate.console)","ItemStack.matches(j.card,console.insertedCartridge())","HomeSystems.isCurrent(s.connection)","hostValid(host,s)","authorizedStart(other,j.second,s.connection)","j.gate.live(st.tick)"})assertTrue(s.contains(expected),expected);}
    @Test void snapshotRunsOnExistingWorkerAndNeverLoadsIntoExecutionHost()throws Exception{String s=source("client/SfcPlayback");assertTrue(s.contains("session.executionHost()"));assertTrue(s.contains("!session.executionHost()"));assertFalse(s.contains("session.port()=="));assertTrue(s.contains("if(nextFrame!=request.frame())"));assertTrue(s.contains("core.loadState(replacement.bytes)"));assertTrue(s.indexOf("core.loadState(replacement.bytes)")>s.indexOf("while(running)"));assertTrue(s.contains("nextFrame=request.frame()"));}
    @Test void abortReleasesBudgetAndCandidateRuntimeButKeepsPhysicalLoanAndP1Frame()throws Exception{String s=source("server/SfcHomeServer");String abort=s.substring(s.indexOf("private static void abortJoin"),s.indexOf("public static void ready"));assertTrue(abort.contains("st.transfer=null"));assertTrue(abort.contains("new SfcHomeNetwork.Stopped(s.id,s.epoch,reason)"));assertFalse(abort.contains("release(server,j.second"));assertFalse(abort.contains("s.frame="));assertFalse(abort.contains("reset("));assertFalse(abort.contains("loadState("));assertTrue(s.contains("st.transfer!=null"));}
}
