package cn.piq.sfchome.server;

import org.junit.jupiter.api.Test;
import java.security.MessageDigest;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

final class SfcRepairLedgerTest {
    private static final UUID HOST=new UUID(1,1),PEER=new UUID(2,2),LEASE=new UUID(3,3);
    private static String hash(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
    private static void frames(SfcRepairLedger ledger,int count){while(count>0){int n=Math.min(4,count),first=ledger.next();int[]a=new int[n],b=new int[n];for(int i=0;i<n;i++){a[i]=(first+i)&4095;b[i]=(4095-first-i)&4095;}ledger.append(first,a,b);count-=n;}}
    private static SfcRepairLedger.Repair start(SfcRepairLedger l,byte[] state,long tick)throws Exception{String expected=hash(state);assertTrue(l.report(HOST,true,600,expected).isEmpty());var mismatches=l.report(PEER,false,600,"0".repeat(64));assertEquals(1,mismatches.size());return l.start(mismatches.getFirst(),LEASE,tick);}
    @Test void reportOrderAndMatchingState(){var l=new SfcRepairLedger();frames(l,600);assertTrue(l.report(PEER,false,600,"a".repeat(64)).isEmpty());assertTrue(l.report(HOST,true,600,"a".repeat(64)).isEmpty());assertTrue(l.report(PEER,false,600,"b".repeat(64)).isEmpty());}
    @Test void reportsCannotInventFutureNonperiodicOrReplayedFrames(){var l=new SfcRepairLedger();frames(l,600);for(int frame:new int[]{-1,0,1,599,601,1200})assertTrue(l.report(PEER,false,frame,"a".repeat(64)).isEmpty());assertTrue(l.report(HOST,true,600,"b".repeat(64)).isEmpty());assertEquals(1,l.report(PEER,false,600,"a".repeat(64)).size());assertTrue(l.report(PEER,false,600,"c".repeat(64)).isEmpty());}
    @Test void hostKeepsAdvancingWhileOnePeerRepairs()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1,2,3},10);assertNotNull(r);assertTrue(l.isolated(PEER));assertFalse(l.isolated(HOST));frames(l,120);assertEquals(720,l.next());assertEquals(120,l.replay(600).p1().length);assertNull(l.start(new SfcRepairLedger.Mismatch(PEER,600,r.sha),LEASE,11));}
    @Test void chunksAreBoundedOrderedAndHashValidated()throws Exception{var l=new SfcRepairLedger();frames(l,600);byte[] bytes=new byte[SfcRepairLedger.CHUNK+17];new Random(1).nextBytes(bytes);var r=start(l,bytes,0);assertFalse(r.append(UUID.randomUUID(),600,bytes.length,0,r.sha,new byte[]{1},1));assertFalse(r.append(r.token,599,bytes.length,0,r.sha,new byte[]{1},1));assertFalse(r.append(r.token,600,bytes.length,1,r.sha,new byte[]{1},1));assertTrue(r.append(r.token,600,bytes.length,0,r.sha,Arrays.copyOfRange(bytes,0,SfcRepairLedger.CHUNK),1));assertTrue(r.append(r.token,600,bytes.length,SfcRepairLedger.CHUNK,r.sha,Arrays.copyOfRange(bytes,SfcRepairLedger.CHUNK,bytes.length),1));assertEquals(SfcRepairLedger.Phase.SEND,r.phase);assertArrayEquals(Arrays.copyOfRange(bytes,0,SfcRepairLedger.CHUNK),r.part());assertArrayEquals(Arrays.copyOfRange(bytes,SfcRepairLedger.CHUNK,bytes.length),r.part());assertEquals(SfcRepairLedger.Phase.RESTORED,r.phase);assertTrue(r.restored(r.token,600,r.sha,true));}
    @Test void corruptUploadDoesNotBecomeReplay()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1,2},0);assertFalse(r.append(r.token,600,2,0,r.sha,new byte[]{1,3},1));assertNotEquals(SfcRepairLedger.Phase.SEND,r.phase);assertFalse(r.restored(r.token,600,r.sha,true));}
    @Test void stateSizeAndPacketRateAreHardBounds()throws Exception{var l=new SfcRepairLedger();frames(l,600);byte[] state=new byte[10];var r=start(l,state,0);assertFalse(r.append(r.token,600,SfcRepairLedger.MAX_STATE+1,0,r.sha,new byte[]{0},1));for(int i=0;i<8;i++)assertTrue(r.append(r.token,600,10,i,r.sha,new byte[]{0},1));assertFalse(r.append(r.token,600,10,8,r.sha,new byte[]{0},1));assertTrue(r.append(r.token,600,10,8,r.sha,new byte[]{0,0},2));}
    @Test void staleAcknowledgmentsCannotCompleteRepair()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1},0);assertTrue(r.append(r.token,600,1,0,r.sha,new byte[]{1},1));r.part();assertFalse(r.restored(UUID.randomUUID(),600,r.sha,true));assertFalse(r.restored(r.token,601,r.sha,true));assertFalse(r.restored(r.token,600,r.sha,false));assertTrue(r.restored(r.token,600,r.sha,true));assertFalse(r.done(r.token,600,true));r.resume=720;r.phase=SfcRepairLedger.Phase.DONE;assertFalse(r.done(r.token,720,true));frames(l,120);assertFalse(r.done(r.token,719,true));assertTrue(r.done(r.token,720,true));}
    @Test void completionNeedsCurrentHeadAndMayPassOriginalResume()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1},0);r.resume=720;r.phase=SfcRepairLedger.Phase.DONE;frames(l,320);assertFalse(r.done(r.token,720,true));assertFalse(r.done(r.token,799,true));assertTrue(r.done(r.token,800,true));assertTrue(r.done(r.token,916,true));assertTrue(r.done(r.token,920,true));assertFalse(r.done(r.token,921,true));assertFalse(r.done(UUID.randomUUID(),916,true));assertFalse(r.done(r.token,916,false));assertEquals(920,l.next());assertTrue(l.isolated(PEER));}
    @Test void historyWrapKeepsOnlyExactRecentFrames(){var l=new SfcRepairLedger();frames(l,SfcRepairLedger.HISTORY+40);assertThrows(IllegalStateException.class,()->l.replay(39));var r=l.replay(40);assertEquals(256,r.p1().length);for(int i=0;i<256;i++){assertEquals((40+i)&4095,r.p1()[i]);assertEquals((4095-40-i)&4095,r.p2()[i]);}assertEquals(0,l.replay(l.next()).p1().length);}
    @Test void cancelReleasesBytesButKeepsCooldown()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1},100);l.cancel();assertFalse(l.isolated(PEER));assertNull(l.active());assertNull(l.start(new SfcRepairLedger.Mismatch(PEER,600,r.sha),LEASE,1299));assertNotNull(l.start(new SfcRepairLedger.Mismatch(PEER,600,r.sha),LEASE,1300));}
    @Test void timeoutExactlyThirtySeconds()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1},100);assertTrue(r.live(699));assertFalse(r.live(700));assertFalse(r.append(r.token,600,1,0,r.sha,new byte[]{1},700));}
    @Test void detachDiscardsOnlyThatParticipantsHistory()throws Exception{var l=new SfcRepairLedger();frames(l,600);var r=start(l,new byte[]{1},0);l.forget(PEER);assertNull(l.active());assertTrue(l.report(PEER,false,600,r.sha).isEmpty());assertEquals(600,l.next());}
    @Test void noRepeatedRepairFromOldMismatchAfterStart()throws Exception{var l=new SfcRepairLedger();frames(l,600);start(l,new byte[]{1},0);l.cancel();frames(l,600);assertTrue(l.report(HOST,true,1200,"a".repeat(64)).isEmpty());}
    @Test void noncontiguousHistoryFailsClosed(){var l=new SfcRepairLedger();assertThrows(IllegalArgumentException.class,()->l.append(1,new int[]{0},new int[]{0}));assertThrows(IllegalArgumentException.class,()->l.append(0,new int[]{4096},new int[]{0}));assertEquals(0,l.next());}
    @Test void invalidLateMaskDoesNotPartiallyAppendHistory(){var l=new SfcRepairLedger();assertThrows(IllegalArgumentException.class,()->l.append(0,new int[]{1,4096},new int[]{0,0}));assertEquals(0,l.next());l.append(0,new int[]{2},new int[]{3});assertArrayEquals(new int[]{2},l.replay(0).p1());}
    @Test void backpressureRetainsExactChunkUntilTransportAdmitsIt()throws Exception{var l=new SfcRepairLedger();frames(l,600);byte[] bytes=new byte[SfcRepairLedger.CHUNK+1];Arrays.fill(bytes,(byte)7);var r=start(l,bytes,0);assertTrue(r.append(r.token,600,bytes.length,0,r.sha,Arrays.copyOf(bytes,SfcRepairLedger.CHUNK),1));assertTrue(r.append(r.token,600,bytes.length,SfcRepairLedger.CHUNK,r.sha,new byte[]{7},2));byte[] pending=r.peekPart();for(int i=0;i<100;i++)assertArrayEquals(pending,r.peekPart());assertEquals(0,r.sent);r.sentPart(pending.length);assertEquals(SfcRepairLedger.CHUNK,r.sent);assertArrayEquals(new byte[]{7},r.peekPart());assertThrows(IllegalStateException.class,()->r.sentPart(0));r.sentPart(1);assertEquals(SfcRepairLedger.Phase.RESTORED,r.phase);assertNull(r.peekPart());}
    @Test void frameGapUsesLatestCanonicalCheckpointAndNotPeerDigest(){var l=new SfcRepairLedger();assertNull(l.latest(PEER));frames(l,1200);l.report(HOST,true,600,"a".repeat(64));l.report(HOST,true,1200,"b".repeat(64));l.report(PEER,false,1200,"c".repeat(64));var point=l.latest(PEER);assertEquals(1200,point.frame());assertEquals("b".repeat(64),point.expected());assertEquals(PEER,point.player());}
}
