package cn.piq.sfchome.server;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class SfcServerSourceContractTest {
    private String source(String path)throws Exception{return Files.readString(Path.of("src/main/java/cn/piq/sfchome/"+path+".java"));}
    @Test void commonEntryRegistersHooksWithoutClientCore()throws Exception{String s=source("SfcHomeMod");assertTrue(s.contains("SfcHomeServer.register()"));assertTrue(s.contains("SfcHomeNetwork::register"));assertFalse(s.contains("WasmSfcCore"));assertFalse(s.contains("cn.piq.sfchome.client"));}
    @Test void sessionCarriesLeaseAndVarIntInput()throws Exception{String s=source("net/SfcHomeNetwork");assertTrue(s.contains("UUID controllerLease"));assertTrue(s.contains("b.writeUUID(v.controllerLease)"));assertTrue(s.contains("b.writeVarInt(v.buttonMask)"));assertTrue(s.contains("readByteArray(CHUNK)"));}
    @Test void actualStartChecksBothEndpoints()throws Exception{String s=source("server/SfcHomeServer");String start=s.substring(s.indexOf("private static boolean powerOn("),s.indexOf("private static void sendRuntime("));assertTrue(start.contains("preflight(p,c,true)"));assertTrue(s.contains("List.of(c.console().getBlockPos(),c.television().getBlockPos())"));assertTrue(s.contains("event.getUseBlock()==TriState.FALSE"));assertTrue(s.contains("HomeSystems.isCurrent(c)"));}
    @Test void copyAndRemoteComputerGatesRemain()throws Exception{String s=source("server/SfcCartridgeEditorService");for(String x:new String[]{"e.level.getBlockEntity(e.pos)!=e.computer","p.getItemInHand(e.hand)!=e.stack","ItemStack.isSameItemSameComponents(e.stack,e.snapshot)","p.inventoryMenu.slots","p.distanceToSqr(e.pos.getCenter())>25"})assertTrue(s.contains(x),x);}
    @Test void inFlightBytesOnlyReleasedByCompletion()throws Exception{String s=source("server/SfcCartridgeEditorService");assertTrue(s.contains("()->{e.committingCover=null;e.commitRevoked=false;st.uploadBudget.release(data.length);}"));assertTrue(s.contains("finally{completed.run();}"));assertTrue(s.contains("st.lastUpload.getOrDefault(p.getUUID()"));}
    @Test void noSymlinkReadAndCanonicalRom()throws Exception{String s=source("server/SfcRomStore");assertTrue(s.contains("StandardOpenOption.READ,LinkOption.NOFOLLOW_LINKS"));assertTrue(s.contains("SfcRomImage.fromBytes"));assertTrue(s.contains("StandardOpenOption.CREATE_NEW"));assertFalse(s.contains("REPLACE_EXISTING"));}
    @Test void sourceMetadataNamespaceMustBeCompound()throws Exception{String s=source("data/SfcCartridgeData");assertTrue(s.contains("!root.contains(KEY,10)"));assertTrue(s.contains("getComponentsPatch()"));}
    @Test void invalidLoadedCartridgeIsNotDeleted()throws Exception{String s=source("world/SfcHomeConsoleBlockEntity");assertFalse(s.contains("!SfcCartridgeData.supported(cartridge))cartridge=ItemStack.EMPTY"));assertTrue(s.contains("insertedCartridge(){return cartridge.copy();}"));}
    @Test void guiGateReleaseDoesNotDependOnLastMask()throws Exception{String s=source("client/SfcHomeClient");assertTrue(s.contains("!active&&!inactiveReleased"));assertTrue(s.contains("if(active)inactiveReleased=false"));assertFalse(s.contains("!active&&lastMask!=0"));}
    @Test void inputWatchdogStartsAfterReadyAndOnlyOccupiedPortsExpire()throws Exception{String s=source("server/SfcHomeServer");assertTrue(s.contains("s.clock=new SfcFrameClock(s.hostReady.targetFps());s.health.start(state(server).tick)"));String tick=s.substring(s.indexOf("private static void tick("),s.indexOf("private static void stop("));assertTrue(tick.indexOf("if(s.clock==null)")<tick.indexOf("s.health.expiredPort("));assertTrue(s.contains("!s.health.packet(port,st.tick)"));assertTrue(tick.contains("for(Lease l:s.ports.clone())if(l!=null&&s.health.expiredPort(l.port,st.tick))release(server,l"));assertTrue(s.contains("s.inputs[port].offer(r.sequence(),input.mask(),input.release()))release(p.getServer(),lease"));}
}
