package cn.piq.fcarcade.cabinet;

import java.util.UUID;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CabinetRoomLedgerTest {
    final CabinetRoomLedger<String> ledger=new CabinetRoomLedger<>();
    final UUID host=UUID.randomUUID(),guest=UUID.randomUUID();
    CabinetRoomLedger.Room<String> room(int n){var room=ledger.open(host,"cabinet","mame",n,0);assertNotNull(room);return room;}
    CabinetRoomLedger.Member joined(CabinetRoomLedger.Room<String> r){assertTrue(ledger.ready(host,r.id,r.host().id,0));return ledger.join(guest,r,0);}
    @Test void capacityIsExplicitOneThroughFour(){for(int n:new int[]{-1,0,5,100})assertNull(ledger.open(host,"a","mame",n,0));assertNotNull(room(3));}
    @Test void fourRoomsAndOneRoomPerPlayer(){for(int n=0;n<4;n++)assertNotNull(ledger.open(UUID.randomUUID(),"cab"+n,"mame",4,0));assertNull(ledger.open(host,"fifth","mame",4,0));}
    @Test void duplicateTargetAndPlayerCannotCreateRooms(){room(4);assertNull(ledger.open(host,"second","mame",4,0));assertNull(ledger.open(guest,"cabinet","mame",4,0));}
    @Test void onlyCurrentHostCanReady(){var r=room(4);assertNull(ledger.join(guest,r,0));assertFalse(ledger.ready(guest,r.id,r.host().id,0));assertFalse(ledger.ready(host,UUID.randomUUID(),r.host().id,0));assertTrue(ledger.ready(host,r.id,r.host().id,0));assertNotNull(ledger.join(guest,r,0));}
    @Test void fixedSeatsDoNotReorderWhenGuestLeaves(){var r=room(4);var p2=joined(r);var p3=ledger.join(UUID.randomUUID(),r,0);var p4=ledger.join(UUID.randomUUID(),r,0);assertEquals(1,p2.port);assertEquals(2,p3.port);assertEquals(3,p4.port);assertNull(ledger.join(UUID.randomUUID(),r,0));assertEquals(1,ledger.remove(guest,p2.id).size());assertSame(p3,r.members[2]);assertSame(p4,r.members[3]);var newer=ledger.join(guest,r,1);assertEquals(1,newer.port);assertNotEquals(p2.id,newer.id);}
    @Test void linkedPrimaryAndSecondaryHaveSeparateTwoSeatRanges(){var r=room(4);assertTrue(ledger.ready(host,r.id,r.host().id,0));var p3=ledger.join(guest,r,0,2,4);assertEquals(2,p3.port);var p2=ledger.join(UUID.randomUUID(),r,0,1,2);assertEquals(1,p2.port);assertNull(ledger.join(UUID.randomUUID(),r,0,1,2));var p4=ledger.join(UUID.randomUUID(),r,0,2,4);assertEquals(3,p4.port);assertNull(ledger.join(UUID.randomUUID(),r,0,2,4));ledger.remove(guest,p3.id);assertNull(ledger.join(UUID.randomUUID(),r,1,1,2));assertEquals(2,ledger.join(guest,r,1,2,4).port);}
    @Test void unlinkedRoomCannotAllocateSecondaryPorts(){var r=room(2);joined(r);assertNull(ledger.join(UUID.randomUUID(),r,0,2,4));assertNull(ledger.join(UUID.randomUUID(),r,0,0,2));assertNull(ledger.join(UUID.randomUUID(),r,0,1,5));}
    @Test void retiredMembershipCannotInputHeartbeatReadyOrRemoveReplacement(){var r=room(2);var old=joined(r);ledger.remove(guest,old.id);var newer=ledger.join(guest,r,1);assertNull(ledger.input(guest,r.id,old.id,999,1,1));assertFalse(ledger.heartbeat(guest,old.id,1));assertFalse(ledger.ready(guest,r.id,old.id,1));assertTrue(ledger.remove(guest,old.id).isEmpty());assertSame(newer,ledger.player(guest));}
    @Test void hostDepartureClosesAllWithoutPromotion(){var r=room(4);joined(r);ledger.join(UUID.randomUUID(),r,0);assertEquals(3,ledger.remove(host,r.host().id).size());assertTrue(ledger.all().isEmpty());assertTrue(ledger.allMembers().isEmpty());assertNull(ledger.player(guest));}
    @Test void cannotJoinTwoRoomsOrRemoveOtherPlayer(){var r=room(2);var g=joined(r);assertNull(ledger.join(guest,r,1));assertTrue(ledger.remove(host,g.id).isEmpty());assertSame(g,ledger.member(g.id));}
    @Test void inputRequiresReadyOwnerRoomSequenceAndTwelveBits(){var r=room(4);assertNull(ledger.input(host,r.id,r.host().id,0,1,0));var g=joined(r);assertNull(ledger.input(host,r.id,g.id,0,1,0));assertNull(ledger.input(guest,UUID.randomUUID(),g.id,0,1,0));assertNull(ledger.input(guest,r.id,g.id,-1,1,0));assertNull(ledger.input(guest,r.id,g.id,0,4096,0));assertNotNull(ledger.input(guest,r.id,g.id,0,4095,0));assertNull(ledger.input(guest,r.id,g.id,0,0,0));assertEquals(4095,g.mask);}
    @Test void tapEdgesSurviveSameTickAndIndependentForwardSequence(){var r=room(2);var g=joined(r);var down=ledger.input(guest,r.id,g.id,100,1,0);var up=ledger.input(guest,r.id,g.id,101,0,0);assertNotNull(down);assertNotNull(up);assertEquals(1,down.sequence());assertEquals(2,up.sequence());assertFalse(up.reset());assertEquals(0,up.mask());}
    @Test void forcedClearIsPerPortAndNextInputRestoresSameMember(){var r=room(4);var g=joined(r);ledger.input(host,r.id,r.host().id,0,2,10);ledger.input(guest,r.id,g.id,0,1,0);assertTrue(ledger.silence(39).isEmpty());var changes=ledger.silence(40);assertEquals(1,changes.size());assertEquals(g.id,changes.getFirst().member());assertTrue(changes.getFirst().reset());assertEquals(2,r.host().mask);assertTrue(ledger.silence(40).isEmpty());assertEquals(3,ledger.input(guest,r.id,g.id,1,1,41).sequence());}
    @Test void silenceAlsoFlushesQueuedTapAfterItsZeroEdge(){var r=room(2);var g=joined(r);ledger.input(guest,r.id,g.id,0,1,0);ledger.input(guest,r.id,g.id,1,0,0);assertEquals(1,ledger.silence(40).size());assertEquals(0,g.mask);}
    @Test void unchangedInputRefreshesSilenceNotLease(){var r=room(2);var g=joined(r);ledger.input(guest,r.id,g.id,0,1,0);assertNull(ledger.input(guest,r.id,g.id,1,1,30));assertTrue(ledger.silence(40).isEmpty());assertEquals(80,g.expires);assertEquals(1,ledger.silence(70).size());}
    @Test void leaseCannotBeRevivedAtExactDeadlineOrByWrongOwner(){var r=room(2);var g=joined(r);assertFalse(ledger.heartbeat(host,g.id,1));assertTrue(ledger.heartbeat(guest,g.id,79));assertEquals(159,g.expires);assertFalse(ledger.heartbeat(guest,g.id,159));assertNull(ledger.valid(guest,r.id,g.id,159));}
    @Test void sixteenEventBurstThenRateViolationMarksOnlyThatGuest(){var r=room(4);var g=joined(r);for(int n=0;n<16;n++)assertNotNull(ledger.input(guest,r.id,g.id,n,(n&1)==0?1:0,0));assertNull(ledger.input(guest,r.id,g.id,16,1,0));assertTrue(g.rateLimited);assertFalse(r.host().rateLimited);assertEquals(1,ledger.remove(guest,g.id).size());assertSame(r,ledger.get(r.id));assertNotNull(ledger.input(host,r.id,r.host().id,0,1,0));}
    @Test void unchangedHeartbeatAndResetShareTheSameEventBudget(){var r=room(2);var g=joined(r);for(int n=0;n<15;n++)ledger.input(guest,r.id,g.id,n,0,0);assertNotNull(ledger.resetInput(guest,r.id,g.id,15,0));assertNull(ledger.input(guest,r.id,g.id,16,0,0));assertTrue(g.rateLimited);}
    @Test void inputAndResetShareSequenceButTapZeroIsNotAReset(){var r=room(2);var g=joined(r);assertNotNull(ledger.input(guest,r.id,g.id,0,1,0));assertFalse(ledger.input(guest,r.id,g.id,1,0,0).reset());assertNull(ledger.resetInput(guest,r.id,g.id,1,0));var reset=ledger.resetInput(guest,r.id,g.id,2,0);assertTrue(reset.reset());assertEquals(0,reset.mask());assertNull(ledger.input(guest,r.id,g.id,2,1,0));assertNotNull(ledger.input(guest,r.id,g.id,3,1,0));}
    @Test void tokenRefillIsFortyPerSecondAndDoesNotAccumulateUnboundedCredit(){var r=room(2);var g=joined(r);long sequence=0;for(int n=0;n<16;n++)ledger.input(guest,r.id,g.id,sequence++,0,0);for(int tick=1;tick<=20;tick++){ledger.input(guest,r.id,g.id,sequence++,0,tick);ledger.input(guest,r.id,g.id,sequence++,0,tick);}assertFalse(g.rateLimited);assertEquals(0,g.inputTokens);ledger.heartbeat(guest,g.id,20);for(int n=0;n<16;n++)ledger.input(guest,r.id,g.id,sequence++,0,60);assertNull(ledger.input(guest,r.id,g.id,sequence,0,60));assertTrue(g.rateLimited);}
    @Test void admittedEdgesStayBoundedUnderFiftyHzCoreConsumption(){var r=room(2);var g=joined(r);long sequence=0;int queue=0,max=0;for(int n=0;n<16;n++){if(ledger.input(guest,r.id,g.id,sequence++,(sequence&1)==0?1:0,0)!=null)queue++;}max=queue;for(int tick=1;tick<=200;tick++){if(tick%40==0)ledger.heartbeat(guest,g.id,tick);for(int n=0;n<2;n++)if(ledger.input(guest,r.id,g.id,sequence++,(sequence&1)==0?1:0,tick)!=null)queue++;max=Math.max(max,queue);queue=Math.max(0,queue-(tick%2==0?3:2));}assertFalse(g.rateLimited);assertTrue(max<=18,"burst + one producer tick stays far below 128");assertTrue(queue<=2);}
    @Test void windowRejectsNegativeAndOverbudgetAndReleasesExactlyAtTwenty(){var w=new CabinetRoomLedger.Window();assertFalse(w.allow(-1,1,100));assertFalse(w.allow(0,-1,100));assertFalse(w.allow(0,101,100));assertTrue(w.allow(0,60,100));assertTrue(w.allow(19,40,100));assertFalse(w.allow(19,1,100));assertTrue(w.allow(20,60,100));assertFalse(w.allow(20,1,100));}
}
