modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-or-later"

[[mods]]
modId="piq_sfc_home"
version="${version}"
displayName="方块电玩：SFC"
authors="PIQ"
description='''Super Famicom home hardware addon for Game Console televisions and its existing SFC core. No commercial ROMs included.'''

[[dependencies.piq_sfc_home]]
modId="neoforge"
type="required"
versionRange="[${neo_min_version},22)"
ordering="NONE"
side="BOTH"

[[dependencies.piq_sfc_home]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.piq_sfc_home]]
modId="piq_fc_arcade"
type="required"
versionRange="[0.31.0-alpha.76.41,0.31.0-alpha.77)"
ordering="AFTER"
side="BOTH"

[[dependencies.piq_sfc_home]]
modId="piq_sfc_arcade"
type="required"
versionRange="[0.2.0-alpha.10,0.3.0)"
ordering="AFTER"
side="BOTH"
