package cn.piq.sfchome.client;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class SfcCardEditorSourceTest {
    private String source(String name)throws Exception{return Files.readString(Path.of("src/main/java/cn/piq/sfchome/client/"+name+".java"));}
    @Test void listReplacesPathInputAndFullNameTooltipExists()throws Exception{String s=source("SfcCardEditorScreen");assertFalse(s.contains("pathField"));assertTrue(s.contains("library.visible(layout.rows())"));assertTrue(s.contains("DeviceUi.row"));assertTrue(s.contains("entry.local()?\"本地待上传\":\"服务器库\""));assertTrue(s.contains("button.setTooltip"));assertTrue(s.contains("DeviceLayout.browser(width,height,2)"));assertTrue(s.contains("layout.details()"));assertTrue(s.contains("DeviceUi.Tone.PRIMARY"));assertTrue(s.contains("CartridgeWorkbenchLayout.of(layout)"));for(String control:new String[]{"name","saveName","players","gamesTab","coversTab","search","refresh","romFolder","coverFolder","previous","next","close","clearCover","restoreCover"})assertTrue(s.contains("workbench."+control+"()"),control);assertTrue(s.contains("SfcWorkbenchDisplay.original(entry)"));assertTrue(s.contains("visibleSelection()"));}
    @Test void filesUseBoundedLibraryWorkerAndNoCommonPool()throws Exception{String s=source("SfcCardEditorScreen");assertTrue(s.contains("LocalRomLibrary.submit"));assertTrue(s.contains("LocalRomLibrary.validateFile(chosen)"));assertTrue(s.contains("LocalRomLibrary.scan(prepared"));assertFalse(s.contains("CompletableFuture"));assertFalse(s.contains("Files.list"));}
    @Test void lateRepliesNeedSameConnectionScreenTokenAndRevision()throws Exception{String s=source("SfcCardEditorScreen");for(String p:new String[]{"minecraft.screen==this","minecraft.getConnection()==connection","!token().equals(message.token())","!scanWork.accepts(ticket)","!importWork.accepts(ticket)","scanWork.close();importWork.close()","void removed(){cancel();}","message.message().endsWith(\"编辑已取消\")","请放好 ROM 后重新打开电脑","onClose();return;"})assertTrue(s.contains(p),p);}
    @Test void resizeDoesNotResetDraftOrRestartUploadAndBackgroundNeverBlurs()throws Exception{String s=source("SfcCardEditorScreen");assertTrue(s.contains("titleField.setValue(library.title())"));assertTrue(s.contains("searchField.setValue(searchQuery)"));assertTrue(s.contains("library.query(value);covers.query(value);rebuildRows()"));assertTrue(s.contains("searchField.moveCursorTo("));assertTrue(s.contains("if(!initialScan)"));assertFalse(s.contains("titleField.setValue(message.title())"));assertTrue(s.contains("extends cn.piq.fcarcade.client.ui.DeviceScreen"));assertFalse(s.contains("void renderBackground("));assertFalse(s.contains("super.renderBackground"));String shared=Files.readString(Path.of("../piq-fc-arcade/src/main/java/cn/piq/fcarcade/client/ui/DeviceScreen.java"));assertTrue(shared.contains("final void renderBackground("));assertFalse(shared.contains("super.renderBackground("));}
    @Test void successfulUploadUsesExactHashTitleGuardAndSharedSfcDirectory()throws Exception{String s=source("SfcCardEditorScreen");assertTrue(s.contains("phase==Phase.FINISHING&&uploadTitle!=null&&uploadTitle.afterUpload"));assertTrue(s.contains("ROM 已写入；名称未完成"));assertTrue(s.contains("LocalRomLibrary.sfcDirectory(FMLPaths.GAMEDIR.get())"));String p=source("cabinet/SfcCabinetProvider");assertTrue(p.contains("LocalRomLibrary.sfcDirectory(FMLPaths.GAMEDIR.get())"));assertTrue(p.contains("romExtensions(){return Set.of(\".sfc\",\".smc\")"));}
}
