package cn.piq.sfchome.client;

import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SfcWorkbenchDisplayTest {
    private static final String HASH="0123456789abcdef".repeat(4);
    @Test void currentServerRomUsesActualCardNameNotAHashGuess(){var row=SfcCardLibrary.Row.server(HASH,HASH+".sfc",32768);assertEquals("我的游戏",SfcWorkbenchDisplay.name(row,HASH,"我的游戏"));assertEquals(HASH+".sfc",row.name());assertEquals(HASH,row.hash());}
    @Test void unnamedServerHashHasShortExplicitlyUnknownLabel(){var row=SfcCardLibrary.Row.server(HASH,HASH+".smc",32768);assertEquals("未命名游戏 · 01234567",SfcWorkbenchDisplay.name(row,"","other"));assertTrue(SfcWorkbenchDisplay.original(row).contains(HASH+".smc"));assertTrue(SfcWorkbenchDisplay.original(row).contains("SHA-256："+HASH));}
    @Test void ordinaryNamesAreNeverGuessedOrRenamed(){for(String n:new String[]{"Super Game.sfc","马里奥.smc","01234567.sfc",HASH+"-copy.sfc",HASH+".png"})assertEquals(n,SfcWorkbenchDisplay.name(SfcCardLibrary.Row.server(HASH,n,12),"",null));}
    @Test void hashNameMatchingIsExactAndCaseInsensitive(){String upper=HASH.toUpperCase();assertEquals("未命名游戏 · "+upper.substring(0,8),SfcWorkbenchDisplay.name(SfcCardLibrary.Row.server(HASH,upper+".SFC",12),"",null));assertEquals("未命名游戏 · 01234567",SfcWorkbenchDisplay.name(SfcCardLibrary.Row.server(HASH,HASH,12),"",null));}
    @Test void localIdentityAndFilenameRemainUntouched(){var row=SfcCardLibrary.Row.local(Path.of(HASH+".sfc"),HASH+".sfc",12);assertEquals(HASH+".sfc",SfcWorkbenchDisplay.name(row,"","title"));assertTrue(SfcWorkbenchDisplay.original(row).contains(row.path().toString()));assertEquals("本地待上传",SfcWorkbenchDisplay.source(row));assertEquals("服务器库",SfcWorkbenchDisplay.source(SfcCardLibrary.Row.server(HASH,"游戏.sfc",12)));}
    @Test void emptyCurrentTitleFallsBackWithoutInventingName(){var row=SfcCardLibrary.Row.server(HASH,HASH+".sfc",12);assertEquals("未命名游戏 · 01234567",SfcWorkbenchDisplay.name(row,HASH," "));assertEquals("未命名卡带",SfcWorkbenchDisplay.current(""));assertEquals("未选择",SfcWorkbenchDisplay.source(null));}
    @Test void compactDetailsNeverExceedAvailableTextLines(){assertEquals(0,SfcWorkbenchDisplay.details("待应用封面","名称","本地 PNG",0).length);assertArrayEquals(new String[]{"待应用封面 · 名称"},SfcWorkbenchDisplay.details("待应用封面","名称","本地 PNG",1));assertArrayEquals(new String[]{"待应用封面 · 名称","来源：本地 PNG"},SfcWorkbenchDisplay.details("待应用封面","名称","本地 PNG",2));assertArrayEquals(new String[]{"待写入游戏","名称：名称","来源：服务器已同步"},SfcWorkbenchDisplay.details("待写入游戏","名称","服务器已同步",3));}
    @Test void aliasSearchKeepsRawHashIdentityAndFilenameSearch(){var row=SfcCardLibrary.Row.server(HASH,HASH+".sfc",12);var library=new SfcCardLibrary("我的卡");library.labels(r->SfcWorkbenchDisplay.name(r,HASH,"我的卡"));library.server(List.of(row),HASH);library.query("我的卡");assertEquals(List.of(row),library.filtered());library.query(HASH.substring(8,20));assertEquals(List.of(row),library.filtered());assertEquals("server:"+HASH,library.selected().key());assertEquals(HASH+".sfc",library.selected().name());assertEquals(HASH,library.selected().hash());}
    @Test void friendlyDefaultDraftRemainsNotDirtyAndTracksNextSelection(){var hashRow=SfcCardLibrary.Row.server(HASH,HASH+".sfc",12);var named=SfcCardLibrary.Row.server("other","游戏.smc",12);var library=new SfcCardLibrary("旧标题");library.labels(r->SfcWorkbenchDisplay.name(r,"",""));library.server(List.of(hashRow,named),"");library.select(hashRow);assertEquals("未命名游戏 · 01234567",library.title());library.title(library.title());assertFalse(library.titleDirty());library.select(named);assertEquals("游戏.smc",library.title());assertFalse(library.titleDirty());}
    @Test void manuallyEditedDraftSurvivesFriendlyLabelsAndRefresh(){var row=SfcCardLibrary.Row.server(HASH,HASH+".sfc",12);var library=new SfcCardLibrary("旧标题");library.labels(r->SfcWorkbenchDisplay.name(r,"",""));library.server(List.of(row),"");library.title("手改标题");library.select(row);library.server(List.of(row),"");assertEquals("手改标题",library.title());assertTrue(library.titleDirty());assertEquals(row,library.selected());}
    @Test void sharedSearchCanHideSelectionWithoutLosingDraftOrIdentity(){var rom=new SfcCardLibrary("草稿");var cover=new SfcCardLibrary("");var selected=SfcCardLibrary.Row.server(HASH,"one.sfc",12);rom.server(List.of(selected),HASH);cover.local(List.of(SfcCardLibrary.Row.local(Path.of("two.png"),"two.png",12)));rom.query("two");cover.query("two");assertTrue(rom.filtered().isEmpty());assertEquals(1,cover.filtered().size());assertEquals(selected,rom.selected());assertEquals("草稿",rom.title());rom.query("");cover.query("");assertTrue(rom.filtered().contains(rom.selected()));}
}
