package cn.piq.retro.worker;

import com.sun.jna.Memory;
import java.io.*;
import java.lang.reflect.Proxy;
import java.net.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;
import static cn.piq.retro.worker.WorkerProtocol.*;

/** Real software-core probe; diagnostic ROM is generated by the existing original test fixture. */
public final class GenericWorkerProbe {
    static int checks;
    static void check(boolean value, String message) { checks++; if (!value) throw new AssertionError(message); }
    public static void main(String[] args) throws Exception {
        if (args.length != 4) throw new IllegalArgumentException("worker-classpath jna core work-root");
        Path root = Path.of(args[3]).toAbsolutePath(); Files.createDirectories(root);
        pixelTests(root);
        var factory = Class.forName("cn.piq.fcarcade.libretro.worker.WorkerProbe").getDeclaredMethod("diagnosticRom");
        factory.setAccessible(true);
        byte[] rom = (byte[]) factory.invoke(null);
        try (Child a = new Child(args, root); Child b = new Child(args, root)) {
            a.load(rom, false); b.load(rom, false);
            boolean color = false, sound = false;
            for (int i = 0; i < 120; i++) {
                Frame x = a.run(1, VIDEO | AUDIO, retro(i), retro(255-i), 0);
                Frame y = b.run(1, VIDEO | AUDIO, retro(i), retro(255-i), 0);
                check(Arrays.equals(x.video, y.video), "two-process RGBA determinism");
                check(Arrays.equals(x.audio, y.audio), "two-process stereo determinism");
                check(Arrays.equals(a.memory(), b.memory()), "two-process RAM determinism");
                for (short sample : x.audio) sound |= sample != 0;
                for (int p = 0; p < x.video.length; p += 4) color |= (x.video[p] | x.video[p+1] | x.video[p+2]) != 0;
            }
            check(color && sound, "real video and audio produced");
            a.run(3, 0, retro(0xa5), retro(0x5a), 0);
            check(mask(a.memory(), 16) == 0xa5, "first RetroPad-to-NES buttons");
            check(mask(a.memory(), 32) == 0x5a, "second RetroPad-to-NES buttons");
            byte[] state = a.save(); a.restore(state); b.restore(state);
            Frame skipped = a.run(30, 0, 0, 0, 0);
            check(skipped.video.length == 0 && skipped.audio.length == 0, "output suppression has empty wire output");
            for (int i = 0; i < 30; i++) b.run(1, VIDEO | AUDIO, 0, 0, 0);
            check(Arrays.equals(a.memory(), b.memory()), "batch output suppression does not skip emulation");
            Frame x = a.run(1, VIDEO | AUDIO, retro(33), retro(66), 0), y = b.run(1, VIDEO | AUDIO, retro(33), retro(66), 0);
            check(Arrays.equals(x.video, y.video), "batch matches single-step final video");
            check(Arrays.equals(x.audio, y.audio), "batch matches single-step future audio");
            a.restore(state); b.restore(state);
            for (int i = 0; i < 60; i++) {
                x = a.run(1, VIDEO | AUDIO, retro(i), retro(i ^ 255), 0);
                y = b.run(1, VIDEO | AUDIO, retro(i), retro(i ^ 255), 0);
                check(Arrays.equals(x.video, y.video) && Arrays.equals(x.audio, y.audio), "cross-process native restore output");
            }
            a.out.writeInt(RESET); a.out.flush(); a.ok(); a.metadata();
            a.run(5, VIDEO | AUDIO, 0, 0, 0);
            System.out.println("stateBytes=" + state.length);
        }
        try (Child gun = new Child(args, root)) {
            gun.load(rom, true);
            gun.run(10, VIDEO, 0, 0, 65536);
            gun.run(3, VIDEO, 0, 0, 65536 | 131072);
            check((gun.memory()[48] & 16) != 0, "Mesen Zapper trigger");
            check((gun.memory()[48] & 8) != 0, "Mesen Zapper offscreen dark");
            gun.run(10, VIDEO, 0, 0, (120 << 8) | 128);
            check(gun.memory()[49] == 1, "Mesen Zapper onscreen light");
        }
        try (Child bad = new Child(args, root)) {
            bad.load(rom, false);
            bad.out.writeInt(RUN); bad.out.writeInt(1); bad.out.writeInt(3); bad.out.writeInt(65536); bad.out.flush();
            check(!bad.in.readBoolean() && bad.in.readUTF().contains("RetroPad"), "invalid pad rejected before native run");
        }
        try (Child bad = new Child(args, root)) {
            bad.load(rom, false);
            bad.out.writeInt(RESTORE); bad.out.writeInt(MAX_STATE + 1); bad.out.flush();
            check(!bad.in.readBoolean() && bad.in.readUTF().contains("length"), "oversized state rejected before allocation");
        }
        System.out.println("PASS generic-worker checks=" + checks);
    }
    static int retro(int nes) { return (nes & 0xfc) | ((nes & 1) << 8) | ((nes & 2) >>> 1); }
    static int mask(byte[] ram, int at) { int value = 0; for (int i = 0; i < 8; i++) value |= (ram[at+i] & 1) << i; return value; }
    static void pixelTests(Path root) throws Exception {
        var fake = (GenericLibretroWorker.Retro) Proxy.newProxyInstance(GenericWorkerProbe.class.getClassLoader(),
                new Class[]{GenericLibretroWorker.Retro.class}, (proxy, method, args) -> null);
        try (var engine = new GenericLibretroWorker.Engine(fake, root); Memory pixels = new Memory(16)) {
            for (int format = 0; format <= 2; format++) {
                engine.pixelFormat = format;
                if (format == 1) { pixels.setInt(0, 0x00ff0000); pixels.setInt(4, 0x0000ff00); }
                else { pixels.setShort(0, (short) (format == 0 ? 0x7c00 : 0xf800)); pixels.setShort(2, (short) (format == 0 ? 0x03e0 : 0x07e0)); }
                engine.video(pixels, 2, 1, format == 1 ? 8 : 4); engine.checkCallback();
                check(Arrays.equals(engine.frame, new byte[]{-1,0,0,-1,0,-1,0,-1}), "pixel format " + format);
                byte[] before = engine.frame.clone(); engine.video(null, 2, 1, 0);
                check(Arrays.equals(before, engine.frame), "duplicate frame preserves cached pixels");
            }
            engine.devices = new int[]{1, 1, 1, 1}; engine.pads = new int[]{65535, 0x8000, 0x1234, 0xabcd};
            check(engine.input(3, 1, 0, 256) == (short) 0xabcd, "fourth RetroPad 16-bit mask");
            check(engine.input(1, 1, 0, 15) == 1, "high digital button");
            check(engine.input(4, 1, 0, 0) == 0, "out of range port neutral");
            engine.collectAudio = true; engine.sample((short) -32768, (short) 32767);
            check(engine.audioCount == 2 && engine.samples[0] == -32768 && engine.samples[1] == 32767, "stereo not mixed");
            engine.collectAudio = false; engine.sample((short) 1, (short) 2);
            check(engine.audioCount == 2, "suppressed audio is not accumulated");
            engine.timing(50.0, 48000.0);
            check(engine.fps == 50.0 && engine.sampleRate == 48000.0, "generic timing retains PAL and native sample rate");
            var geometry = new GenericLibretroWorker.Geometry();
            geometry.baseWidth = 1; geometry.baseHeight = 2; geometry.maxWidth = 2; geometry.maxHeight = 2; geometry.aspectRatio = 0;
            engine.geometry(geometry, true);
            check(engine.width == 1 && engine.height == 2 && engine.aspect == 0.5f, "dynamic geometry and natural aspect");
            engine.pixelFormat = 1; pixels.setInt(0, 0x00ff0000); pixels.setInt(8, 0x000000ff);
            engine.video(pixels, 1, 2, 8); engine.checkCallback();
            check(Arrays.equals(engine.frame, new byte[]{-1,0,0,-1,0,0,-1,-1}), "padded row pitch");
            engine.video(pixels, 3, 1, 12);
            try { engine.checkCallback(); throw new AssertionError("out-of-bounds geometry accepted"); }
            catch (IOException expected) { check(true, "declared maximum geometry enforced"); }
        }
        try { GenericLibretroWorker.Engine.validateGeometry(4096, 4096); throw new AssertionError("oversized frame accepted"); }
        catch (IOException expected) { check(true, "video byte cap"); }
    }
    record Frame(byte[] video, short[] audio) {}
    static final class Child implements AutoCloseable {
        final Process process; final Socket socket; final DataInputStream in; final DataOutputStream out;
        Child(String[] args, Path root) throws Exception {
            Path work = Files.createTempDirectory(root, "generic-");
            String token = UUID.randomUUID().toString().replace("-", "");
            InetAddress loopback = InetAddress.getByAddress(new byte[]{127,0,0,1});
            try (ServerSocket server = new ServerSocket(0, 1, loopback)) {
                server.setSoTimeout(15000);
                String java = Path.of(System.getProperty("java.home"), "bin", "java.exe").toString();
                process = new ProcessBuilder(java, "-Xmx192m", "-cp", args[0] + File.pathSeparator + args[1],
                        "cn.piq.retro.worker.GenericLibretroWorker", Integer.toString(server.getLocalPort()), token,
                        Path.of(args[2]).toAbsolutePath().toString(), work.toString()).redirectErrorStream(true)
                        .redirectOutput(work.resolve("worker.log").toFile()).start();
                try {
                    socket = server.accept(); socket.setSoTimeout(15000); socket.setTcpNoDelay(true);
                    in = new DataInputStream(new BufferedInputStream(socket.getInputStream()));
                    out = new DataOutputStream(new BufferedOutputStream(socket.getOutputStream()));
                    check(in.readInt() == MAGIC && in.readInt() == VERSION && in.readUTF().equals(token), "authenticated v2 hello");
                    out.writeInt(ACK); out.flush();
                } catch (Throwable error) { process.destroyForcibly(); throw error; }
            }
        }
        void ok() throws IOException { if (!in.readBoolean()) throw new IOException(in.readUTF()); }
        void metadata() throws IOException {
            int w=in.readInt(), h=in.readInt(), mw=in.readInt(), mh=in.readInt(); float aspect=in.readFloat();
            double fps=in.readDouble(), rate=in.readDouble(); int format=in.readInt();
            check(w==256 && h==240 && mw>=w && mh>=h && aspect>0 && fps>60 && fps<61 && rate==44100 && format==1, "Mesen AV metadata");
        }
        void load(byte[] rom, boolean gun) throws IOException {
            LinkedHashMap<String,String> options = new LinkedHashMap<>();
            options.put("mesen_region", "NTSC"); options.put("mesen_ramstate", "All 0s (Default)"); options.put("mesen_audio_sample_rate", "44100");
            options.put("mesen_ntsc_filter", "Disabled");
            for (String direction : List.of("left","right","up","down")) options.put("mesen_overscan_"+direction, "None");
            for (String key : List.of("hdpacks","nospritelimit","fake_stereo","swap_duty_cycle","disable_noise_mode_flag","shift_buttons_clockwise","fdsfastforwardload","fdsautoinsertdisk")) options.put("mesen_"+key, "disabled");
            options.put("mesen_overclock", "None"); options.put("mesen_screenrotation", "None"); options.put("mesen_controllerturbospeed", "Disabled");
            out.writeInt(LOAD); out.writeUTF("Mesen"); out.writeUTF("nes"); out.writeBoolean(true); out.writeInt(2);
            out.writeInt(257); out.writeInt(gun ? 262 : 257); out.writeInt(gun ? 1 : 0); out.writeInt(options.size());
            for (var entry : options.entrySet()) { out.writeUTF(entry.getKey()); out.writeUTF(entry.getValue()); }
            out.writeInt(rom.length); out.write(rom); out.flush(); ok();
            check(in.readUTF().equals("Mesen"), "core identity"); in.readUTF(); metadata();
        }
        Frame run(int count, int mask, int p1, int p2, int gun) throws IOException {
            out.writeInt(RUN); out.writeInt(count); out.writeInt(mask);
            for (int i=0;i<count;i++) { out.writeInt(p1); out.writeInt(p2); out.writeInt(gun); }
            out.flush(); ok(); metadata(); in.readBoolean();
            int n=in.readInt(); check(n==((mask&VIDEO)==0?0:256*240*4), "video wire size"); byte[] video=in.readNBytes(n);
            int size=in.readInt(); check(size>=0 && size<=MAX_AUDIO_FRAMES*2 && size%2==0, "stereo wire size");
            short[] audio=new short[size]; for(int i=0;i<size;i++) audio[i]=in.readShort(); return new Frame(video,audio);
        }
        byte[] memory() throws IOException { out.writeInt(MEMORY); out.writeInt(2); out.flush(); ok(); int n=in.readInt(); check(n==2048,"RAM size"); return in.readNBytes(n); }
        byte[] save() throws IOException { out.writeInt(SAVE); out.flush(); ok(); int n=in.readInt(); check(n>0&&n<=MAX_STATE,"native state bound"); return in.readNBytes(n); }
        void restore(byte[] state) throws IOException { out.writeInt(RESTORE); out.writeInt(state.length); out.write(state); out.flush(); ok(); }
        public void close() throws Exception {
            try { if(process.isAlive()) { out.writeInt(CLOSE); out.flush(); ok(); } } catch(IOException expected) { }
            finally { socket.close(); if(!process.waitFor(5,TimeUnit.SECONDS)) { process.destroyForcibly(); process.waitFor(5,TimeUnit.SECONDS); } }
        }
    }
}
