"""Final-JAR-only watch23 scope/old-method audit. Never compiles production or reruns media workers."""
from __future__ import annotations
import argparse,copy,json,os,re,sys,tempfile,tomllib
from pathlib import Path
import verify_retro_alpha19 as compat
import prepare_watch23 as stage
from freeze_fc_core_alpha19 import read_jar

ROOT=compat.ROOT;TOOLS=Path(__file__).resolve().parent;META=compat.META;MANIFEST=compat.MANIFEST
EXPECTED={'fc':'B7BF04BEEA5F58E8E9C0DFA23E1BD8F2CAF6B11455085D843F568B42D9021686','sfc':'ADF7172C0997983A61C0566AAEE4AE6F19C7D574D6D5B1971490EB69F4B92393','native':stage.BASELINES['native'][1]}
def require(ok,why):
    if not ok:raise AssertionError(why)
def classes(prefix,names):return {prefix+n+'.class' for n in names.split()}
FC='cn/piq/fcarcade/';SFC='cn/piq/sfchome/'
ADDED={
 'fc':classes(FC,'''cabinet/CabinetRooms$1 cabinet/WatchAnchor cabinet/WatchBudget cabinet/WatchBudget$Window cabinet/WatchDescriptor cabinet/WatchLedger cabinet/WatchLedger$Candidate cabinet/WatchLedger$Lease cabinet/WatchLedger$Source cabinet/WatchNetwork cabinet/WatchNetwork$Available cabinet/WatchNetwork$ClientSink cabinet/WatchNetwork$Heartbeat cabinet/WatchNetwork$HostDemand cabinet/WatchNetwork$Media cabinet/WatchNetwork$Release cabinet/WatchNetwork$Start cabinet/WatchNetwork$Stop cabinet/WatchNetwork$Stream cabinet/WatchProvider cabinet/WatchProviders cabinet/WatchService cabinet/WatchService$Control cabinet/WatchService$Live cabinet/WatchService$State cabinet/WatchSource client/cabinet/WatchAudio client/cabinet/WatchMediaStream client/watch/CabinetWatchDisplay client/watch/WatchClient client/watch/WatchClient$Demand client/watch/WatchClient$DisplayAdapter client/watch/WatchClient$Setup client/watch/WatchLeaseState'''),
 'sfc':classes(SFC,'''client/SfcWatchClient client/SfcWatchClient$Setup client/SfcWatchDemand client/SfcWatchFrames client/SfcWatchPublisher client/SfcWatchPublisher$Publication server/SfcWatchProvider'''), 'native':set()}
CHANGED={
 'fc':classes(FC,'''cabinet/CabinetMediaSender cabinet/CabinetMediaSender$1 cabinet/CabinetNetwork cabinet/CabinetNetwork$Choose cabinet/CabinetNetwork$Closed cabinet/CabinetNetwork$Heartbeat cabinet/CabinetNetwork$Launch cabinet/CabinetNetwork$Menu cabinet/CabinetNetwork$Release cabinet/CabinetRooms cabinet/CabinetRooms$State client/cabinet/CabinetClientBackends client/cabinet/CabinetClientBackends$Setup''')|{'cn/piq/retro/input/InputOwnership.class'},
 'sfc':classes(SFC,'''SfcHomeMod client/SfcPlayback client/SfcPlayback$Host client/SfcPlayback$MinecraftHost client/SfcPlayback$MinecraftHost$1 client/SfcPlayback$Picture client/SfcPlayback$Restore server/SfcHomeServer server/SfcHomeServer$1 server/SfcHomeServer$Joining server/SfcHomeServer$Lease server/SfcHomeServer$Session server/SfcHomeServer$State'''), 'native':set()}

# Every changed method was independently inspected as ASM instructions, including try/catch and
# invokedynamic bootstrap handles. This is a fixed reviewed artifact, NEVER regenerated by audit().
REVIEW=ROOT/'piq-fc-arcade/design/watch23-asm-inspection-v1.json'
REVIEW_SHA='AFE9552A37DAC20B81AE467B3092E583A124A8A54736C13E6984B048887C3B97'
HOOKS={
 FC+'cabinet/CabinetMediaSender.class':({'clientbound','send','serverbound'},{'clientbound','send','serverbound','watchClientbound','watchServerbound'},set(),'Only payload routing/boolean private dispatcher; window admission, completion and release retained.'),
 FC+'cabinet/CabinetNetwork.class':({'register'},{'register'},set(),'One additive WatchNetwork.register call after original registrations.'),
 FC+'cabinet/CabinetRooms.class':({'<clinit>','close','logout','media','stopped','tick'},{'<clinit>','close','logout','media','stopped','tick','registerWatchProvider','watchSource'},{'WATCH_PROVIDER','watchRegistered'},'Add read-only provider; append spectator relay after player delivery and exact-source shutdown/tick hooks.'),
 FC+'client/cabinet/CabinetClientBackends.class':({'drainMedia','lambda$startGame$4','render','seat','stop'},{'drainMedia','lambda$startGame$4','render','seat','stop','hasLocalSession','needsMedia','updateMediaDemand','watchDemand'},{'watchExpires','watchers'},'Only media demand OR spectators, drop stale outbound when not demanded, and spectator state reset; old keyboard, lease, input and permission methods retained.'),
 'cn/piq/retro/input/InputOwnership.class':(set(),{'occupied'},set(),'Add synchronized read-only occupied query; ownership mutations retained.'),
 SFC+'SfcHomeMod.class':({'<init>'},{'<init>'},set(),'One additive provider registration.'),
 SFC+'client/SfcPlayback.class':({'close','run'},{'close','run','watchFrame'},{'mediaFailed','watchPicture'},'Retain last immutable Picture and optional P1-only media callback; callback Runtime/Linkage failure isolated, original pacing/capture/restore/input/core/backup control flow retained.'),
 SFC+'client/SfcPlayback$Host.class':(set(),{'mediaClosed','mediaFrame'},set(),'Two default no-op media-only methods.'),
 SFC+'client/SfcPlayback$MinecraftHost.class':(set(),{'mediaClosed','mediaFrame'},set(),'Forward the two optional hooks to SfcWatchPublisher only.'),
 SFC+'server/SfcHomeServer$Session.class':({'<init>'},{'<init>'},{'watchSource'},'Initialize one random visual source UUID; all original constructor assignments retained.'),
 SFC+'server/SfcHomeServer.class':(set(),{'watchParticipant','watchSources'},set(),'Add two read-only snapshots; every old server control/invitation method unchanged.')}

def method_audit(dumps,review):
    result={};protected=0;changed=0
    for kind,data in dumps.items():
        for name,before in data['old'].items():
            after=data['new'][name];ref=review[kind];allowed=HOOKS.get(name,(set(),set(),set(),'All old fields, signatures and instructions unchanged.'))
            for key in ('name','access','super','interfaces'):require(before[key]==after[key],name+' class API '+key)
            require(all(after['fields'].get(f)==v for f,v in before['fields'].items()),name+' old field altered')
            fields=set(after['fields'])-set(before['fields']);require({f.split(' ')[0]for f in fields}==allowed[2],name+' new fields')
            b=before['methods'];a=after['methods'];old_hooks={m for m in b if m not in a or b[m]!=a[m]};new_hooks={m for m in a if m not in b or b[m]!=a[m]}
            require({m.split('(')[0]for m in old_hooks}==allowed[0] and len(old_hooks)==len(allowed[0]),name+' changed old method set')
            require({m.split('(')[0]for m in new_hooks}==allowed[1] and len(new_hooks)==len(allowed[1]),name+' changed/new method set')
            require(before==ref['old'][name] and after==ref['new'][name],name+' reviewed instruction/field fingerprint mismatch')
            retained=sorted(set(b)-old_hooks);protected+=len(retained);changed+=len(old_hooks)
            result[name]={'old_methods_identical':retained,'reviewed_old_hook_methods':sorted(old_hooks),'reviewed_new_hook_methods':sorted(new_hooks),'added_fields':sorted(fields),'review':allowed[3],
                          'hook_sha256':{m:compat.digest((m+'\n'+a[m]).encode())for m in sorted(new_hooks)}}
    return {'old_identical_methods':protected,'reviewed_changed_old_methods':changed,'classes':result,'normalization':'ASM SKIP_DEBUG/SKIP_FRAMES, full instructions, try/catch, field/method operands, invokedynamic bootstrap handles; no production class loaded.'}

def metadata(kind,old,new):
    if kind=='native':require(old[META]==new[META] and old[MANIFEST]==new[MANIFEST],'Native metadata changed');return
    before=tomllib.loads(old[META].decode());after=tomllib.loads(new[META].decode())
    mod,oldv,newv=('piq_fc_arcade','0.31.0-alpha.22','0.31.0-alpha.23')if kind=='fc'else('piq_sfc_home','0.1.0-alpha.10','0.1.0-alpha.11')
    targets=[m for m in before['mods'] if m['modId']==mod];require(len(targets)==1 and targets[0]['version']==oldv,'Baseline mod identity');targets[0]['version']=newv
    if kind=='sfc':
        dep=[d for d in before['dependencies'][mod] if d['modId']=='piq_fc_arcade'];require(len(dep)==1,'Baseline dependency');dep[0]['versionRange']='[0.31.0-alpha.23,0.32.0)'
    require(before==after,'Unexpected metadata change '+kind)
    require(old[MANIFEST].replace(oldv.encode(),newv.encode())==new[MANIFEST],'Unexpected manifest change '+kind)

def classify(kind,old,new):
    require(not set(old)-set(new),'Old entries deleted '+kind)
    require(set(new)-set(old)==ADDED[kind],'Unapproved added class/resource '+kind+': '+repr(sorted((set(new)-set(old))^ADDED[kind])))
    metadata(kind,old,new);changed=[];same=[]
    for name,raw in old.items():
        if new[name]==raw:same.append(name)
        elif name in (META,MANIFEST):continue
        else:require(name in CHANGED[kind],'Unapproved old change '+kind+': '+name);changed.append(name)
    for name in ADDED[kind]|set(changed):require(new[name][:4]==b'\xca\xfe\xba\xbe','Bad production class '+name)
    for name in ADDED[kind]:
        if '/client/' not in name:require(b'net/minecraft/client/'not in new[name] and b'cn/piq/fcarcade/client/'not in new[name],'Common links client '+name)
    assets=[n for n in old if n.startswith(('assets/','data/'))];require(all(new[n]==old[n] for n in assets),'Existing resources changed')
    return {'added_classes':sorted(ADDED[kind]),'changed_classes':sorted(changed),'unchanged_entries':len(same),'unchanged_classes':sum(n.endswith('.class')for n in same),'all_old_assets_and_data_byte_identical':len(assets),'deleted_entries':0}

def asm_dump(jar,entries,cp,tmp):
    return compat.parse_last_json(compat.run([compat.JAVA/'java.exe','-Djava.awt.headless=true','@'+str(cp),'Watch23BytecodeProbe',jar,*sorted(entries)],tmp))

def main():
    sys.stdout.reconfigure(encoding='utf-8');p=argparse.ArgumentParser(description=__doc__);p.add_argument('--stage',type=Path,required=True);p.add_argument('--report',type=Path,required=True);p.add_argument('--inspect',action='store_true');a=p.parse_args()
    require(not a.report.exists(),'Refuse existing report');paths={k:a.stage/n for k,n in stage.NAMES.items()};jars={};old={};hashes={};oldpaths={}
    for kind,path in paths.items():
        hashes[kind],_,jars[kind]=read_jar(path);jars[kind]=stage.clean(jars[kind]);require(hashes[kind]==EXPECTED[kind],'Frozen final SHA '+kind)
        name,sha=stage.BASELINES[kind];oldpaths[kind]=stage.BASE/name;actual,_,old[kind]=read_jar(oldpaths[kind]);old[kind]=stage.clean(old[kind]);require(actual==sha,'Frozen baseline SHA '+kind)
    scope={k:classify(k,old[k],jars[k])for k in paths};owners=compat.unique_ownership(jars)
    planned,planned_report=stage.plan()
    for name,raw in planned.items():require((a.stage/name).read_bytes()==raw,'Prepared stage does not reproduce '+name)
    recorded=json.loads((a.stage/'stage-verification.json').read_text(encoding='utf-8'));require(recorded==planned_report,'Stage report differs from reproduction')
    corepath,sha=compat.BASELINES['core'];actual,core=compat.archive(corepath);require(actual==sha,'Frozen SFC core SHA');protected=[n for n in core if n not in(META,MANIFEST)];require(all(jars['sfc'].get(n)==core[n]for n in protected),'Frozen SFC6 core changed')
    negatives=[]
    for label,kind,entry,action in [('old_model','fc','assets/piq_fc_arcade/textures/item/controller_twohand_skin.png','change'),('core','sfc','assets/piq_sfc_arcade/core/piq_sfc_wasm.wasm','change'),('watch_prefix_injection','fc',FC+'cabinet/WatchHiddenProbe.class','add'),('deleted_entry','fc',FC+'cabinet/CabinetTarget.class','delete')]:
        mutant=dict(jars[kind]);mutant.pop(entry,None)if action=='delete'else mutant.__setitem__(entry,b'negative only')
        try:classify(kind,old[kind],mutant)
        except (ValueError,AssertionError):negatives.append(label)
        else:raise AssertionError('Negative accepted '+label)
    dumps={};deps=compat.dependencies()
    with tempfile.TemporaryDirectory(prefix='watch23-final-scope-')as folder:
        tmp=Path(folder);out=tmp/'classes';out.mkdir();empty=tmp/'empty';empty.mkdir();cp=os.pathsep.join(map(str,[out,*deps]));args=tmp/'cp.args';args.write_text('-cp\n"'+cp.replace('\\','/')+'"\n',encoding='utf-8')
        compat.run([compat.JAVA/'javac.exe','@'+str(args),'-encoding','UTF-8','-proc:none','-sourcepath',empty,'-d',out,TOOLS/'qa/Watch23BytecodeProbe.java'],tmp)
        for kind in ('fc','sfc'):
            before=tmp/(kind+'old.jar');after=tmp/(kind+'new.jar');before.write_bytes(oldpaths[kind].read_bytes());after.write_bytes(paths[kind].read_bytes())
            dumps[kind]={'old':asm_dump(before,CHANGED[kind],args,tmp),'new':asm_dump(after,CHANGED[kind],args,tmp)}
    if a.inspect:
        for kind,data in dumps.items():
            for name,before in data['old'].items():
                after=data['new'][name];b=before['methods'];n=after['methods'];print(json.dumps({'kind':kind,'class':name,'added_methods':sorted(set(n)-set(b)),'removed_methods':sorted(set(b)-set(n)),'changed_methods':[m for m in b if m in n and b[m]!=n[m]],'added_fields':sorted(set(after['fields'])-set(before['fields']))},ensure_ascii=False))
        with a.report.open('x',encoding='utf-8')as f:json.dump(dumps,f,ensure_ascii=False,indent=2)
        return
    require(compat.digest(REVIEW.read_bytes())==REVIEW_SHA,'Manually reviewed ASM artifact changed');review=json.loads(REVIEW.read_text(encoding='utf-8'))
    method_report=method_audit(dumps,review)
    mutant=copy.deepcopy(dumps);c=SFC+'server/SfcHomeServer.class';m=next(m for m in mutant['sfc']['new'][c]['methods']if m.startswith('controllerReady('));mutant['sfc']['new'][c]['methods'][m]+='\n    ICONST_1\n'
    try:method_audit(mutant,review)
    except AssertionError:negatives.append('old_controller_method_instruction_change')
    else:raise AssertionError('Protected method negative accepted')
    probe_report=compat.java_probes(paths)
    old_wire={'fc':[n for n in old['fc']if n.endswith('.class')and (n==FC+'FcNetwork.class' or n.startswith(FC+'home/CartridgeNetwork')
                    or re.fullmatch(r'cn/piq/fcarcade/[^/]+Payload(?:\$[^/]*)?\.class',n))],
              'sfc':[n for n in old['sfc']if n.startswith(SFC+'net/')and n.endswith('.class')]}
    require(old_wire['fc'] and old_wire['sfc'],'Missing original protocol inventory')
    for k,names in old_wire.items():require(all(old[k][n]==jars[k][n]for n in names),'Old network bytecode changed '+k)
    room_wire=[n for n in old['fc']if n.startswith(FC+'cabinet/CabinetRoomNetwork')and n.endswith('.class')];require(all(old['fc'][n]==jars['fc'][n]for n in room_wire),'Old room protocol changed')
    for kind,path in paths.items():require(compat.digest(path.read_bytes())==hashes[kind],'Final JAR changed during audit')
    result={'ok':True,'schema':'piq-watch23-final-scope-1','jars':{k:{'path':str(p.resolve()),'sha256':hashes[k]}for k,p in paths.items()},
            'strict_scope':scope,'ownership':owners,'old_method_protection':method_report,'old_network_classes_whole_byte_identical':{k:len(v)for k,v in old_wire.items()},'old_room_protocol_classes_byte_identical':len(room_wire),'old_cabinet_six_records_fields_codecs_and_instructions_identical':True,
            'frozen_sfc6_core_entries_byte_identical':len(protected),'native_and_helper_whole_jar_identical':True,
            'stage_preparer_review':{'reproduces_exact_frozen_bytes':True,'source_and_baseline_hashes_match_record':True,'only_two_explicit_controller_textures_restored':True,'no_class_core_runtime_injected_by_fc_staging':True,'zip_path_crc_duplicate_and_size_guards_reused':True,'note':'Stage uses prefix/stem bounds; this independent audit tightens them to exact class lists, exact metadata deltas and reviewed ASM methods.'},
            'negative_controls_rejected':negatives,'probes':probe_report,'reviewed_asm_artifact':{'path':str(REVIEW),'sha256':REVIEW_SHA},
            'tools_sha256':{str(p.relative_to(ROOT)):compat.digest(p.read_bytes())for p in (Path(__file__),TOOLS/'qa/Watch23BytecodeProbe.java',TOOLS/'prepare_watch23.py')},
            'production_compiled':False,'minecraft_or_native_core_started':False,'network_socket_opened':False,'installed':False,
            'limits':['No actual Minecraft multiplayer/physical-controller/protection-plugin playtest.','FML discovery and old outer codecs do not equal full game bootstrap.','Spectator wire/window and SFC real worker tests are separate teammate final-JAR reports and were not rerun here.']}
    a.report.parent.mkdir(parents=True,exist_ok=True)
    with a.report.open('x',encoding='utf-8')as f:json.dump(result,f,ensure_ascii=False,indent=2)
    print(json.dumps({'ok':True,'report':str(a.report),'old_unchanged_methods':method_report['old_identical_methods'],'fml':probe_report['fml_discovery'],'old_outer_codec':probe_report['sfc_real_neoforge_outer_packet_codec'],'sha256':compat.digest(a.report.read_bytes())},ensure_ascii=False))

if __name__=='__main__':main()
