package cn.piq.retro.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static cn.piq.retro.client.KeyboardRouting.Route.*;
import static cn.piq.retro.client.KeyboardControlState.Mode.*;

class KeyboardRoutingTest {
    @Test void settingsOpensWithoutAnySession(){assertEquals(SETTINGS,KeyboardRouting.route(296,296,90,true,false,false,null,false,false,false));}
    @Test void toggleRequiresPhysicalPresenceButNotCoreAuthorization(){assertEquals(PASS,KeyboardRouting.route(90,296,90,true,false,false,null,true,false,true));assertEquals(PASS,KeyboardRouting.route(90,296,90,true,true,false,LOCKED,true,false,true));assertEquals(TOGGLE,KeyboardRouting.route(90,296,90,true,true,true,PARALLEL,true,false,true));}
    @Test void escapeIsAlwaysMinecraftEvenIfMismapped(){assertEquals(PASS,KeyboardRouting.route(256,256,256,true,true,true,LOCKED,true,false,true));}
    @Test void guiOrFocusLossDoesNotConsumeAnything(){for(int key:new int[]{296,90,74,87})assertEquals(PASS,KeyboardRouting.route(key,296,90,false,true,true,LOCKED,true,false,true));}
    @Test void noPhysicalDeviceMeansAllNormalWorldKeysPass(){for(int key:new int[]{74,75,87,65,32,90})assertEquals(PASS,KeyboardRouting.route(key,296,90,true,false,false,null,true,false,true));}
    @Test void everyPositionModeCapturesGameFunctions(){for(var mode:KeyboardControlState.Mode.values())assertEquals(GAME,KeyboardRouting.route(74,296,90,true,true,true,mode,true,false,false));}
    @Test void parallelCapturesOnlyGameFunctionsAndNonConflictingDirections(){assertEquals(GAME,KeyboardRouting.route(74,296,90,true,true,true,PARALLEL,true,false,false));assertEquals(PASS,KeyboardRouting.route(87,296,90,true,true,true,PARALLEL,true,true,true));assertEquals(GAME,KeyboardRouting.route(265,296,90,true,true,true,PARALLEL,true,true,false));}
    @Test void lockedCapturesMovementButNotUnrelatedHotkeys(){assertEquals(MOVEMENT,KeyboardRouting.route(87,296,90,true,true,true,LOCKED,false,false,true));assertEquals(GAME,KeyboardRouting.route(74,296,90,true,true,true,LOCKED,true,false,true));for(int key:new int[]{76,69,84,81,49,57,290,32})assertEquals(PASS,KeyboardRouting.route(key,296,90,true,true,true,LOCKED,false,false,false),"unrelated MC key "+key);}
    @Test void controlHotkeysWinOverStaleGameAliases(){assertEquals(SETTINGS,KeyboardRouting.route(296,296,90,true,true,true,LOCKED,true,false,true));assertEquals(TOGGLE,KeyboardRouting.route(90,296,90,true,true,true,PARALLEL,true,false,true));}
    @Test void lAdvancementsIsBlockedExactlyWhenItIsAGameFunction(){for(var mode:KeyboardControlState.Mode.values()){assertEquals(PASS,KeyboardRouting.route(76,296,90,true,true,true,mode,false,false,false));assertEquals(GAME,KeyboardRouting.route(76,296,90,true,true,true,mode,true,false,false));assertEquals(PASS,KeyboardRouting.route(76,296,90,true,true,false,mode,true,false,false));}}
    @Test void unknownScancodeOnlyCapturesExactMovementWhileLocked(){for(int key:new int[]{-1000,-1001})assertEquals(PASS,KeyboardRouting.route(key,-1,-1,true,true,true,LOCKED,true,false,true));assertEquals(PASS,KeyboardRouting.route(-1,-1,-1,true,true,true,LOCKED,false,false,false));assertEquals(MOVEMENT,KeyboardRouting.route(-1,-1,-1,true,true,true,LOCKED,false,false,true));for(var mode:new KeyboardControlState.Mode[]{FREE,PARALLEL})assertEquals(PASS,KeyboardRouting.route(-1,-1,-1,true,true,true,mode,false,false,true));assertEquals(PASS,KeyboardRouting.route(-1,-1,-1,true,false,false,LOCKED,false,false,true));assertEquals(PASS,KeyboardRouting.route(-1,-1,-1,false,true,true,LOCKED,false,false,true));}
    @Test void captureOnlyNeverNeedsRuntimeArming(){var s=new KeyboardControlState(KeyboardConfig.Preset.WASD,new int[][]{{76}});s.activate(false,k->false);assertFalse(s.armed());assertEquals(GAME,KeyboardRouting.route(76,296,90,true,true,true,s.mode(),s.gameKey(76),s.directionOnly(76),false));assertEquals(0,s.mask(255));}
    @Test void movementLockDoesNotDependOnGameNeutral(){var s=new KeyboardControlState(KeyboardConfig.Preset.WASD,new int[][]{{74}});s.toggle();s.activate(true,k->true);assertFalse(s.armed());assertEquals(MOVEMENT,KeyboardRouting.route(32,296,90,true,true,true,s.mode(),false,false,true));assertEquals(PASS,KeyboardRouting.route(69,296,90,true,true,true,s.mode(),false,false,false));}
    @Test void remappedWorldDirectionTakesPrecedenceOnlyInUnlockedPosition(){assertEquals(PASS,KeyboardRouting.route(265,296,90,true,true,true,PARALLEL,true,true,true));assertEquals(GAME,KeyboardRouting.route(265,296,90,true,true,true,LOCKED,true,true,true));}
    @Test void functionMappedToMovementAlwaysBelongsToSimulator(){for(var mode:KeyboardControlState.Mode.values())assertEquals(GAME,KeyboardRouting.route(87,296,90,true,true,true,mode,true,false,true));}
    @Test void jumpSneakSprintPassWhenUnlockedAndAreSuppressedWhenLocked(){for(int key:new int[]{32,340,341}){assertEquals(PASS,KeyboardRouting.route(key,296,90,true,true,true,PARALLEL,false,false,true));assertEquals(MOVEMENT,KeyboardRouting.route(key,296,90,true,true,true,LOCKED,false,false,true));}}
    @Test void oldNineArgumentApiRemainsCallable(){assertEquals(GAME,KeyboardRouting.route(74,296,90,true,true,true,PARALLEL,true,false));assertEquals(PASS,KeyboardRouting.route(74,296,90,true,true,false,PARALLEL,true,false));}
    @Test void captureOnlyCannotStealAdmittedOwner(){assertFalse(KeyboardRouting.mayReplace(true,true,true,false));assertFalse(KeyboardRouting.mayReplace(true,true,true,true));}
    @Test void admittedOwnerCanReplaceIdleCaptureAndCaptureCannotThrashAnotherCapture(){assertTrue(KeyboardRouting.mayReplace(true,false,true,true));assertFalse(KeyboardRouting.mayReplace(true,false,true,false));}
    @Test void vanishedOwnerCannotKeepKeyboardAndIncomingMustStillBePresent(){for(boolean currentAuthorized:new boolean[]{false,true})for(boolean incomingAuthorized:new boolean[]{false,true}){assertTrue(KeyboardRouting.mayReplace(false,currentAuthorized,true,incomingAuthorized));assertFalse(KeyboardRouting.mayReplace(false,currentAuthorized,false,incomingAuthorized));assertFalse(KeyboardRouting.mayReplace(true,currentAuthorized,false,incomingAuthorized));}}
}
