package cn.piq.retro.client;

import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KeyboardControlStateTest {
    private static int[][] keys(KeyboardConfig.Profile p,KeyboardConfig.Preset preset){return KeyboardConfig.presetKeys(p,preset).stream().map(k->new int[]{k}).toArray(int[][]::new);}
    private static KeyboardControlState state(){return new KeyboardControlState(KeyboardConfig.Preset.LEGACY,new int[][]{{75,88},{74,90},{-1}});}
    private static KeyboardControlState wasd(){return new KeyboardControlState(KeyboardConfig.Preset.WASD,keys(KeyboardConfig.Profile.SFC,KeyboardConfig.Preset.WASD));}
    @Test void everyPresetStartsAutomaticAndUnlocked(){for(var p:KeyboardConfig.Profile.values())for(var preset:KeyboardConfig.Preset.values()){var s=new KeyboardControlState(preset,keys(p,preset));assertEquals(KeyboardControlState.Mode.PARALLEL,s.mode());s.activate(true,k->false);assertTrue(s.enabled());assertTrue(s.armed());}}
    @Test void initialHeldFunctionRequiresNeutral(){var s=state();s.activate(true,k->k==75);assertFalse(s.armed());s.key(75,1);assertEquals(0,s.mask(0));s.activate(true,k->false);assertTrue(s.armed());s.key(75,1);assertEquals(1,s.mask(0));}
    @Test void wasdFunctionWorksWhileDirectionsRemainWorldMovement(){var s=wasd();s.activate(true,k->k==87,k->k==87);assertTrue(s.armed());assertFalse(s.key(87,1,true));assertEquals(0,s.mask(0,k->k==87));s.key(74,1,false);assertEquals(1,s.mask(0,k->k==87));}
    @Test void unlockKeepsAutomaticGameplayAfterNeutral(){var s=state();s.toggle();s.activate(true,k->false);s.key(75,1);s.toggle();assertEquals(KeyboardControlState.Mode.PARALLEL,s.mode());assertEquals(0,s.mask(0));s.activate(true,k->false);s.key(75,1);assertEquals(1,s.mask(0));}
    @Test void afterFocusLossOldHeldKeyCannotReturn(){var s=state();s.activate(true,k->false);s.key(75,1);assertTrue(s.activate(false,k->true));s.activate(true,k->k==75);assertEquals(0,s.mask(0));s.key(75,2);assertEquals(0,s.mask(0));s.activate(true,k->false);s.key(75,1);assertEquals(1,s.mask(0));}
    @Test void guiPauseIsIdempotentAndRequiresFreshPress(){var s=state();s.activate(true,k->false);s.key(74,1);assertTrue(s.pause());assertFalse(s.pause());s.activate(true,k->false);assertEquals(0,s.mask(0));s.key(74,1);assertEquals(2,s.mask(0));}
    @Test void everyFastPressAndReleaseSurvivesWithoutFramePolling(){var s=state();s.activate(true,k->false);for(int n=0;n<200;n++){assertTrue(s.key(75,1));assertEquals(1,s.mask(0));assertTrue(s.key(75,0));assertEquals(0,s.mask(0));}}
    @Test void repeatsCannotCreateOrResurrectAnEdge(){var s=state();s.activate(true,k->false);assertFalse(s.key(75,2));assertEquals(0,s.mask(0));s.key(75,1);assertFalse(s.key(75,2));s.key(75,0);assertFalse(s.key(75,2));assertEquals(0,s.mask(0));}
    @Test void originalAliasesDoNotReleaseEachOther(){var s=state();s.activate(true,k->false);s.key(75,1);s.key(88,1);s.key(75,0);assertEquals(1,s.mask(0));s.key(88,0);assertEquals(0,s.mask(0));}
    @Test void originalMouseAliasRequiresMouseNeutralAndRetainsKeyboardAlias(){var s=new KeyboardControlState(KeyboardConfig.Preset.LEGACY,new int[][]{{75,-1000}});s.activate(true,k->k==-1000);assertFalse(s.armed());assertEquals(0,s.mask(1));s.activate(true,k->false);assertEquals(1,s.mask(1));s.key(75,1);assertEquals(1,s.mask(0));s.key(75,0);assertEquals(0,s.mask(0));assertTrue(s.gameKey(-1000));}
    @Test void unboundKeysCannotLeakLegacyFallback(){var s=state();s.activate(true,k->false);assertEquals(0,s.mask(7));}
    @Test void replacedKeysForceNeutralAndDropFormerEdges(){var s=state();s.activate(true,k->false);s.key(75,1);assertTrue(s.bindings(new int[][]{{65}}));assertFalse(s.armed());assertEquals(0,s.mask(0));s.activate(true,k->k==65);assertFalse(s.armed());s.activate(true,k->false);assertFalse(s.key(75,1));s.key(65,1);assertEquals(1,s.mask(0));}
    @Test void unchangedBindingsDoNotDisruptHeldState(){var s=state();s.activate(true,k->false);s.key(75,1);assertFalse(s.bindings(new int[][]{{75,88},{74,90},{-1}}));assertEquals(1,s.mask(0));}
    @Test void configureCopiesArraysAndResetsPositionLock(){int[][] k={{75}};var s=new KeyboardControlState(KeyboardConfig.Preset.NUMPAD,k);k[0][0]=74;s.activate(true,x->false);s.key(75,1);assertEquals(1,s.mask(0));s.toggle();s.configure(KeyboardConfig.Preset.WASD,new int[][]{{65}});assertEquals(0,s.mask(0));assertEquals(KeyboardControlState.Mode.PARALLEL,s.mode());}
    @Test void nesNumpadNativeBitOrderIsNotSfcOrder(){var s=new KeyboardControlState(KeyboardConfig.Preset.NUMPAD,keys(KeyboardConfig.Profile.NES,KeyboardConfig.Preset.NUMPAD));s.activate(true,k->false);s.key(321,1);assertEquals(2,s.mask(0));s.key(321,0);s.key(322,1);assertEquals(1,s.mask(0));}
    @Test void arcadeSixButtonsUseAllNativeBits(){var s=new KeyboardControlState(KeyboardConfig.Preset.WASD,keys(KeyboardConfig.Profile.ARCADE,KeyboardConfig.Preset.WASD));s.activate(true,k->false);int[] key={74,75,76,73,79,80},bit={0,1,8,9,10,11};for(int i=0;i<6;i++){s.key(key[i],1);assertEquals(1<<bit[i],s.mask(0));s.key(key[i],0);assertEquals(0,s.mask(0));}}
    @Test void nonGameWasdIsNotConsumedByLegacyState(){var s=state();for(int key:new int[]{87,65,83,68,32,256,297})assertFalse(s.gameKey(key));}
    @Test void returningOwnerDoesNotReuseOldOwnersDownSet(){var a=state();var b=state();a.activate(true,k->false);b.activate(true,k->false);a.key(75,1);a.pause();assertEquals(0,b.mask(0));b.key(74,1);assertEquals(2,b.mask(0));assertEquals(0,a.mask(0));}
    @Test void toggleWhileKeyHeldWaitsForAllCapturedKeys(){var s=state();s.activate(true,k->false);s.key(75,1);s.toggle();s.activate(true,k->k==75);assertFalse(s.armed());s.activate(true,k->k==74);assertFalse(s.armed());s.activate(true,k->false);assertTrue(s.armed());assertEquals(0,s.mask(0));}
    @Test void lockingWhileWalkingRequiresNeutralBeforeDirectionInput(){var s=wasd();s.activate(true,k->k==87,k->k==87);assertTrue(s.armed());s.toggle();s.activate(true,k->k==87,k->k==87);assertFalse(s.armed());s.key(87,2,true);assertEquals(0,s.mask(0));s.activate(true,k->false,k->k==87);s.key(87,1,true);assertEquals(1<<4,s.mask(0,k->k==87));}
    @Test void arrowDirectionsRemainAvailableWhenNotWorldMovement(){var s=new KeyboardControlState(KeyboardConfig.Preset.NUMPAD,keys(KeyboardConfig.Profile.NES,KeyboardConfig.Preset.NUMPAD));s.activate(true,k->false,k->false);s.key(265,1,false);assertEquals(1<<4,s.mask(0,k->false));}
    @Test void customWorldBindingCollisionIsNotLimitedToLiteralWasd(){var s=new KeyboardControlState(KeyboardConfig.Preset.NUMPAD,keys(KeyboardConfig.Profile.NES,KeyboardConfig.Preset.NUMPAD));s.activate(true,k->k==265,k->k==265);assertTrue(s.armed());assertFalse(s.key(265,1,true));assertEquals(0,s.mask(0,k->k==265));}
    @Test void aFunctionAliasIsNeverMistakenForDirectionOnly(){int[][] bindings={{87},{74},{259},{257},{87},{83},{65},{68}};var s=new KeyboardControlState(KeyboardConfig.Preset.LEGACY,bindings);assertFalse(s.directionOnly(87));assertTrue(s.captures(87,true));s.activate(true,k->false,k->true);s.key(87,1,true);assertEquals((1<<4)|1,s.mask(0,k->true));}
    @Test void authorityLossClearsAndCannotInjectWithCaptureOnly(){var s=state();s.activate(true,k->false);s.key(75,1);s.activate(false,k->false);assertFalse(s.enabled());assertFalse(s.armed());s.key(75,1);assertEquals(0,s.mask(255));s.activate(true,k->k==75);assertFalse(s.armed());s.activate(true,k->false);assertEquals(0,s.mask(0));s.key(75,1);assertEquals(1,s.mask(0));}
    @Test void modeStatusExplainsMovementLockWithoutClaimingWholeKeyboardCapture(){var s=state();assertTrue(s.status("Z").contains("可自由移动"));s.toggle();assertTrue(s.status("Z").contains("移动已锁定"));assertTrue(s.status("Z").contains("无关世界快捷键"));s.toggle();assertFalse(s.status("Z").contains("键盘和手柄不操作模拟器"));}
}
