// SPDX-License-Identifier: GPL-3.0-or-later
package cn.piq.mdhome;
import org.junit.jupiter.api.Test;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

class MdPublicAuthorityTest {
    @Test void rejectedPublicNeverFallsBackToPrivate(){var r=new MdContentRouting();var c=new Object();var id=UUID.randomUUID();assertFalse(r.grant(c,id,MdContentRouting.Lane.PUBLIC,false));assertEquals(MdContentRouting.Lane.REJECT,r.route(c,id));assertEquals(MdContentRouting.Lane.REJECT,r.route(c,UUID.randomUUID()));}
    @Test void exactConnectionOnlyEvenWithEqualObjects(){var r=new MdContentRouting();Object a=new String("same"),b=new String("same");var id=UUID.randomUUID();assertTrue(r.grant(a,id,MdContentRouting.Lane.PUBLIC,true));assertEquals(MdContentRouting.Lane.REJECT,r.route(b,id));r.retire(b,id);assertEquals(MdContentRouting.Lane.PUBLIC,r.route(a,id));}
    @Test void endedAndLatePublicTokensCannotStartPrivate(){var r=new MdContentRouting();var c=new Object();var old=UUID.randomUUID();var next=UUID.randomUUID();r.grant(c,old,MdContentRouting.Lane.PUBLIC,true);r.retire(c,old);assertTrue(r.grant(c,next,MdContentRouting.Lane.PRIVATE,true));assertEquals(MdContentRouting.Lane.REJECT,r.route(c,old));assertEquals(MdContentRouting.Lane.PRIVATE,r.route(c,next));}
    @Test void conflictCannotReplaceActiveRoute(){var r=new MdContentRouting();var c=new Object();var id=UUID.randomUUID();r.grant(c,id,MdContentRouting.Lane.PRIVATE,true);assertFalse(r.grant(c,UUID.randomUUID(),MdContentRouting.Lane.PUBLIC,true));assertFalse(r.grant(c,id,MdContentRouting.Lane.PUBLIC,true));assertEquals(MdContentRouting.Lane.PRIVATE,r.route(c,id));}
    @Test void sameGrantIdempotentAndLogoutRevokes(){var r=new MdContentRouting();var c=new Object();var id=UUID.randomUUID();assertTrue(r.grant(c,id,MdContentRouting.Lane.PUBLIC,true));assertTrue(r.grant(c,id,MdContentRouting.Lane.PUBLIC,true));r.clear();assertEquals(MdContentRouting.Lane.REJECT,r.route(c,id));}
    @Test void downloadBeforeGrantAndAfterStopRejected(){var r=new MdContentRouting();var c=new Object();var id=UUID.randomUUID();assertEquals(MdContentRouting.Lane.REJECT,r.route(c,id));r.grant(c,id,MdContentRouting.Lane.PRIVATE,true);assertEquals(MdContentRouting.Lane.PRIVATE,r.route(c,id));r.retire(c,id);assertEquals(MdContentRouting.Lane.REJECT,r.route(c,id));}
    @Test void inputCannotSwitchConnectionWirePortLoanOrReplay(){Object c=new Object();UUID id=UUID.randomUUID();var g=new MdPublicInputGate(c,id,7,1);assertEquals(MdPublicInputGate.Result.REJECT,g.accept(new Object(),7,1,id,0,1,0));assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,8,1,id,0,1,0));assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,7,0,id,0,1,0));assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,7,1,UUID.randomUUID(),0,1,0));assertEquals(MdPublicInputGate.Result.ACCEPT,g.accept(c,7,1,id,0,1,0));assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,7,1,id,0,0,1));assertEquals(MdPublicInputGate.Result.ACCEPT,g.accept(c,7,1,id,1,0,2));}
    @Test void invalidMasksDoNotAdvanceSequence(){var c=new Object();var id=UUID.randomUUID();var g=new MdPublicInputGate(c,id,1,0);assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,1,0,id,1,4096,0));assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,1,0,id,1,-1,0));assertEquals(MdPublicInputGate.Result.ACCEPT,g.accept(c,1,0,id,1,4095,0));}
    @Test void burstRateConsumesReplayAndRecoversNextSecond(){var c=new Object();var id=UUID.randomUUID();var g=new MdPublicInputGate(c,id,1,0);for(int i=0;i<180;i++)assertEquals(MdPublicInputGate.Result.ACCEPT,g.accept(c,1,0,id,i,1,0));assertEquals(MdPublicInputGate.Result.RATE_LIMIT,g.accept(c,1,0,id,180,1,0));assertEquals(MdPublicInputGate.Result.REJECT,g.accept(c,1,0,id,180,1,2_000_000_000L));assertEquals(MdPublicInputGate.Result.ACCEPT,g.accept(c,1,0,id,181,0,2_000_000_000L));}
}
