package cn.piq.pvz.runtime;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;
class PvzJniTest {
    @Test void latestBoundedControls(){var q=new PvzJniInputs();for(int i=0;i<10000;i++)q.input(i,99999,-99999,9,true);var s=q.drain();assertEquals(9999,s.pad());assertEquals(32767,s.x());assertEquals(-32768,s.y());assertEquals(1,s.buttons());assertTrue(s.pointer());assertEquals(0,s.keys().length);}
    @Test void orderedKeyEdges(){var q=new PvzJniInputs();assertTrue(q.key(true,8,0));assertTrue(q.key(false,8,0));assertArrayEquals(new int[]{1,8,0,0,8,0},q.drain().keys());assertEquals(0,q.drain().keys().length);}
    @Test void queueBounded(){var q=new PvzJniInputs();for(int i=0;i<128;i++)assertTrue(q.key(true,0,65));assertFalse(q.key(true,0,65));assertEquals(384,q.drain().keys().length);assertTrue(q.key(true,0,65));}
    @Test void releaseAllHeldAcrossDrainsIsBounded(){var q=new PvzJniInputs();for(int i=1;i<=128;i++){assertTrue(q.key(true,i,0));q.drain();}assertFalse(q.key(true,129,0));q.input(5,1,2,3,true);q.release();var s=q.drain();assertEquals(384,s.keys().length);for(int i=0;i<s.keys().length;i+=3)assertEquals(0,s.keys()[i]);assertEquals(0,s.pad());assertEquals(0,s.buttons());assertFalse(s.pointer());assertTrue(q.key(true,129,0));}
    @Test void invalidKeyBounds(){var q=new PvzJniInputs();assertFalse(q.key(true,-1,0));assertFalse(q.key(true,512,0));assertFalse(q.key(true,513,0));assertFalse(q.key(true,0,0x110000));assertFalse(q.key(true,0,0xD800));assertFalse(q.key(true,0,-1));assertEquals(0,q.drain().keys().length);}
    @Test void commonProfilePinsRealCoreOptions(){var p=PvzJniRuntime.profile();assertEquals("PvZ",p.name());assertEquals("0.25",p.options().get("pvz_gamepad_deadzone"));assertEquals(PvzRuntime.CORE_SHA,p.cores().get("windows-x64").sha256());}
    @Test void experimentalSavesAreDistinct(){var id=UUID.randomUUID();var path=PvzJniWorkspace.savePath(Path.of("storage"),id,"A".repeat(64));assertEquals(Path.of("storage/piq-pvz/jni-common-v1-saves"),path.getParent());assertTrue(path.getFileName().toString().matches("[0-9A-F]{64}"));assertEquals(path,PvzJniWorkspace.savePath(Path.of("storage"),id,"A".repeat(64)));assertNotEquals(path,PvzJniWorkspace.savePath(Path.of("storage"),UUID.randomUUID(),"A".repeat(64)));assertNotEquals(path,PvzJniWorkspace.savePath(Path.of("storage"),id,"B".repeat(64)));assertThrows(IllegalArgumentException.class,()->PvzJniWorkspace.savePath(Path.of("storage"),id,"../old"));}
    @Test void longNativePathsRejectedBeforeLoading()throws Exception{PvzJniWorkspace.checkNativePath(Path.of("a".repeat(160)));assertThrows(java.io.IOException.class,()->PvzJniWorkspace.checkNativePath(Path.of("a".repeat(161))));assertThrows(java.io.IOException.class,()->PvzJniWorkspace.checkNativePath(Path.of("长".repeat(54))));}
    @Test void nativePinMatchesPackagedResource()throws Exception{try(var in=PvzJniBridge.class.getResourceAsStream("/core/pvz/piq-pvz-jni.dll")){assertNotNull(in);assertEquals(PvzJniBridge.SHA,java.util.HexFormat.of().withUpperCase().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(in.readAllBytes())));}}
    @Test void nativeBridgeAvoidsProcessWideMutations()throws Exception{String s=Files.readString(Path.of("native/pvz_jni.cpp"));for(String bad:new String[]{"SetCurrentDirectory","SetDefaultDllDirectories","SetDllDirectory","ExitProcess","std::exit","TerminateProcess"})assertFalse(s.contains(bad),bad);assertTrue(s.contains("wglGetCurrentContext()"));assertTrue(s.contains("GetDirectBufferCapacity(pixels)!=VIDEO"));assertTrue(s.contains("active->owner!=GetCurrentThreadId()"));}
}
