package cn.piq.nativearcade.bridge;

import java.io.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NativeStepProtocolTest {
    interface Writer{void write(DataOutputStream out)throws Exception;}
    byte[] bytes(Writer writer)throws Exception{var b=new ByteArrayOutputStream();writer.write(new DataOutputStream(b));return b.toByteArray();}
    DataInputStream input(byte[] value){return new DataInputStream(new ByteArrayInputStream(value));}
    NativeStepProtocol.Reply round(NativeStepProtocol.Reply value)throws Exception{try(var in=input(bytes(out->NativeStepProtocol.writeReply(out,value)))){var copy=NativeStepProtocol.readReply(in,value.id());assertEquals(0,in.available());return copy;}}
    @Test void helloPreservesFractionalTimingAndVersion()throws Exception{var h=new NativeStepProtocol.Hello(59.18560791015625,48000,4);assertEquals(h,NativeStepProtocol.readHello(input(bytes(out->NativeStepProtocol.writeHello(out,h)))));assertThrows(IllegalArgumentException.class,()->new NativeStepProtocol.Hello(Double.NaN,48000,4));assertThrows(IllegalArgumentException.class,()->new NativeStepProtocol.Hello(60,44100,4));assertThrows(IOException.class,()->NativeStepProtocol.readHello(input(new byte[28])));}
    @Test void fourMasksAreNotRemappedOrDelayedInProtocol()throws Exception{for(int port=0;port<4;port++)for(int bit=0;bit<12;bit++){int[] masks=new int[4];masks[port]=1<<bit;var r=NativeStepProtocol.step(1,masks[0],masks[1],masks[2],masks[3]);var copy=NativeStepProtocol.readRequest(input(bytes(out->NativeStepProtocol.writeCommand(out,r))),1);assertEquals(r,copy);}}
    @Test void idsMustMatchExactlyAndHigherBitsAreRejected()throws Exception{byte[] valid=bytes(out->NativeStepProtocol.writeCommand(out,NativeStepProtocol.step(2,0,0,0,0)));assertThrows(IOException.class,()->NativeStepProtocol.readRequest(input(valid),1));assertThrows(IllegalArgumentException.class,()->NativeStepProtocol.step(0,0,0,0,0));assertThrows(IllegalArgumentException.class,()->NativeStepProtocol.step(1,0,65535,0,0));assertThrows(IOException.class,()->NativeStepProtocol.readRequest(input(bytes(out->{out.writeInt(999);out.writeLong(1);})),1));}
    @Test void loadCopiesOpaqueStateAndPreservesFrame()throws Exception{byte[] s={1,2,3};var r=NativeStepProtocol.load(1,940,s);s[0]=9;assertEquals(1,r.state()[0]);r.state()[0]=8;assertEquals(1,r.state()[0]);var copy=NativeStepProtocol.readRequest(input(bytes(out->NativeStepProtocol.writeRequest(out,r))),1);assertArrayEquals(r.state(),copy.state());assertEquals(940,copy.frame());}
    @Test void malformedStateLengthsRejectedBeforeAllocatingBody()throws Exception{for(int length:new int[]{Integer.MIN_VALUE,-1,0,NativeStepProtocol.MAX_STATE+1,Integer.MAX_VALUE})assertThrows(IOException.class,()->NativeStepProtocol.readRequest(input(bytes(out->{out.writeInt(3);out.writeLong(1);out.writeLong(0);out.writeInt(length);})),1));}
    @Test void truncationNeverBecomesPartialCommand()throws Exception{byte[] data=bytes(out->NativeStepProtocol.writeRequest(out,NativeStepProtocol.load(1,1,new byte[17])));for(int length=0;length<data.length;length++){byte[] truncated=Arrays.copyOf(data,length);assertThrows(IOException.class,()->NativeStepProtocol.readRequest(input(truncated),1));}}
    @Test void initialEmptyFrameHasRealTimingAndAudioButNoInventedPixels()throws Exception{var f=new NativeStepProtocol.Frame(1,1,59.18560791015625,48000,false,false,0,0,0,0,new int[0],new short[]{7,-7});var copy=(NativeStepProtocol.Frame)round(f);assertFalse(copy.hasVideo());assertFalse(copy.freshVideo());assertEquals(f.fps(),copy.fps());assertArrayEquals(f.pcm48k(),copy.pcm48k());assertEquals(0,copy.abgr().length);}
    @Test void frameOwnsPixelAndPcmArraysAndPreservesRotation()throws Exception{int[] p={0xff112233,0xffabcdef};short[] a={Short.MIN_VALUE,Short.MAX_VALUE};var f=new NativeStepProtocol.Frame(1,2,60,48000,true,false,2,1,2,3,p,a);p[0]=0;a[0]=0;var copy=(NativeStepProtocol.Frame)round(f);assertEquals(0xff112233,copy.abgr()[0]);assertEquals(Short.MIN_VALUE,copy.pcm48k()[0]);assertEquals(3,copy.rotation());copy.abgr()[0]=0;assertEquals(0xff112233,copy.abgr()[0]);}
    @Test void strictHeaderRejectsImpossibleDimensionsOrAudioPairs(){assertThrows(IllegalArgumentException.class,()->new NativeStepProtocol.Frame(1,1,60,48000,false,true,0,0,0,0,new int[0],new short[0]));assertThrows(IllegalArgumentException.class,()->NativeStepProtocol.frameBounds(true,true,2049,1,1,0,0));assertThrows(IllegalArgumentException.class,()->NativeStepProtocol.frameBounds(true,true,1,1,Float.NaN,0,0));assertThrows(IllegalArgumentException.class,()->NativeStepProtocol.frameBounds(true,true,1,1,1,0,1));assertThrows(IllegalArgumentException.class,()->NativeStepProtocol.frameBounds(false,false,0,0,-0f,0,0));}
    @Test void saveAndLoadAcknowledgmentHaveExplicitCounters()throws Exception{var state=(NativeStepProtocol.State)round(new NativeStepProtocol.State(2,23,new byte[]{4,5}));assertEquals(23,state.frame());assertArrayEquals(new byte[]{4,5},state.state());assertEquals(new NativeStepProtocol.Loaded(3,17),round(new NativeStepProtocol.Loaded(3,17)));assertEquals(new NativeStepProtocol.Closed(4),round(new NativeStepProtocol.Closed(4)));}
    @Test void everyReplyRejectsWrongRequestId()throws Exception{var values=List.of(new NativeStepProtocol.State(1,0,new byte[]{1}),new NativeStepProtocol.Loaded(1,2),new NativeStepProtocol.Closed(1),new NativeStepProtocol.Failure(1,"停止"));for(var v:values)assertThrows(IOException.class,()->NativeStepProtocol.readReply(input(bytes(out->NativeStepProtocol.writeReply(out,v))),2));}
    @Test void errorUtf8IsBoundedAndUnknownReplyFails()throws Exception{assertEquals(new NativeStepProtocol.Failure(1,"核心拒绝"),round(new NativeStepProtocol.Failure(1,"核心拒绝")));assertThrows(IllegalArgumentException.class,()->new NativeStepProtocol.Failure(1,"字".repeat(2000)));assertThrows(IOException.class,()->NativeStepProtocol.readReply(input(bytes(out->{out.writeInt(5);out.writeLong(1);out.writeInt(Integer.MAX_VALUE);})),1));assertThrows(IOException.class,()->NativeStepProtocol.readReply(input(bytes(out->{out.writeInt(99);out.writeLong(1);})),1));}
}
