package cn.piq.fcarcade.client;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class ControllerCaptureSourceTest {
    private String source(String name)throws Exception{return Files.readString(Path.of("src/main/java/cn/piq/fcarcade/"+name+".java"));}
    @Test void idleCaptureHasNoCoreInputOwnershipOrNetworkPath()throws Exception{String c=source("client/ControllerCapture");for(String forbidden:new String[]{"InputOwnership.acquire(","CabinetClientOwner.acquire(","sendToServer(","FcNetwork.","new ClientNesWorker","new SfcPlayback"})assertFalse(c.contains(forbidden),forbidden);assertTrue(c.contains("()->valid(candidate),()->false,()->{},()->{}"));assertTrue(c.contains("mc.getConnection()!=candidate.connection()"));assertTrue(c.contains("mc.level.getBlockEntity(endpoint.getBlockPos())!=endpoint"));assertTrue(c.contains("candidate.provider().matches(mc.player,held,endpoint)"));}
    @Test void presenceRefreshRunsBeforeHeadButOnlyGrantedRuntimeCanSend()throws Exception{String c=source("client/ControllerCapture"),e=source("client/ClientArcadeEvents"),s=source("client/ClientArcadeSession");assertTrue(c.contains("KeyboardInput.registerPresenceRefresh(ControllerCapture::refresh)"));assertTrue(e.contains("session.refreshKeyboardCapture()"));assertTrue(s.contains("this::keyboardPresent,this::keyboardAuthorized,this::releaseControls,this::captureInputEvent"));assertTrue(s.contains("return keyboardPresent()&&(worker!=null||(serverHosted()||netplay!=null)&&workerReady)&&!awaitingSnapshot"));assertTrue(s.contains("ControllerCapture.unique(minecraft.player,stack,controllerLease"));}
    @Test void gunButtonAuthorizationAndSourceTrackingStayInServerBeforeFifo()throws Exception{String s=source("server/ServerArcadeSessions");String input=s.substring(s.indexOf("private void handleInput(ServerPlayer player,ArcadeInputPayload payload,UUID"),s.indexOf("private void handleZapper("));assertTrue(input.indexOf("payload.epoch()!=session.lockstep.epoch()")<input.indexOf("buttonPort("));assertTrue(input.indexOf("HomeZapperService.keyboardLease")<input.indexOf("lockstep.acceptInput("));assertTrue(input.contains("HomeControllerService.authorized(player,session.key.anchor(),session.id,0)"));assertTrue(input.contains("homeRuntime.recordButtons(player.getUUID(),player.connection.getConnection(),physicalLease,assistedGun)"));assertTrue(s.contains("s.homeRuntime.clearGunButtons(old.lease())"));assertTrue(s.contains("s.homeRuntime.clearGunButtons(payload.lease())"));}
}
