package cn.piq.fcarcade.netplay;

import cn.piq.fcarcade.session.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NetplayGunMailboxTest {
    int gun(boolean trigger){return ZapperInput.pack(128,120,false,trigger);}
    @Test void fastClickEdgesAreNotLost(){var q=new NetplayGunMailbox();q.offer(1,1,0,gun(true),0);q.offer(1,2,0,gun(false),1);assertTrue(ZapperInput.trigger(q.next(2).aim()));assertFalse(ZapperInput.trigger(q.next(3).aim()));}
    @Test void movementCoalescesWithoutLosingTriggerOrButtonEdges(){var q=new NetplayGunMailbox();for(int i=0;i<200;i++)assertTrue(q.offer(1,i,0,ZapperInput.pack(i,20,false,true),i));assertEquals(199,ZapperInput.x(q.next(201).aim()));q.offer(1,200,1,gun(true),202);q.offer(1,201,0,gun(true),203);assertEquals(1,q.next(204).buttons());assertEquals(0,q.next(205).buttons());}
    @Test void releaseBarrierFlushesPendingOldPress(){var q=new NetplayGunMailbox();q.offer(1,1,255,gun(true),0);q.offer(2,2,0,ZapperInput.NEUTRAL,1);assertEquals(NetplayGunMailbox.NEUTRAL,q.next(2));assertFalse(q.offer(1,99,255,gun(true),3));assertEquals(NetplayGunMailbox.NEUTRAL,q.next(4));}
    @Test void staleSequenceCannotClearNewLease(){var q=new NetplayGunMailbox();q.offer(2,20,1,gun(true),0);assertFalse(q.offer(3,19,0,ZapperInput.NEUTRAL,1));assertEquals(1,q.next(2).buttons());}
    @Test void timeoutNeutralizesAndRequiresRealRelease(){var q=new NetplayGunMailbox();q.offer(1,1,1,gun(true),0);assertTrue(ZapperInput.trigger(q.next(1).aim()));assertEquals(NetplayGunMailbox.NEUTRAL,q.next(NetplayGunMailbox.TIMEOUT_NANOS+1));assertFalse(q.offer(1,2,1,gun(true),900_000_000));assertTrue(q.offer(1,3,0,gun(false),910_000_000));assertTrue(q.offer(1,4,1,gun(true),920_000_000));assertFalse(ZapperInput.trigger(q.next(930_000_000).aim()));assertTrue(ZapperInput.trigger(q.next(940_000_000).aim()));}
    @Test void overloadedQueueFailsClosed(){var q=new NetplayGunMailbox();for(int i=0;i<32;i++)assertTrue(q.offer(1,i,i%2+1,gun(true),i));assertFalse(q.offer(1,32,3,gun(true),32));assertEquals(NetplayGunMailbox.NEUTRAL,q.next(33));assertFalse(q.offer(1,33,1,gun(true),34));assertTrue(q.offer(1,34,0,ZapperInput.NEUTRAL,35));assertEquals(NetplayGunMailbox.NEUTRAL,q.next(36));}
    @Test void closedAndNeverReceivedAreNeutral(){var q=new NetplayGunMailbox();assertEquals(NetplayGunMailbox.NEUTRAL,q.next(0));q.offer(1,1,1,gun(true),1);q.close();assertEquals(NetplayGunMailbox.NEUTRAL,q.next(2));}
    @Test void coordinatesMapPixelCentersAndFlagsIndependently(){for(int x:new int[]{0,1,127,128,254,255})for(int y:new int[]{0,1,119,120,238,239}){var s=new NetplayGunMailbox.Sample(0,ZapperInput.pack(x,y,false,true));int v=s.coordinates();assertEquals(x,((short)(v>>>16)+32768)*256/65536);assertEquals(y,((short)v+32768)*240/65536);assertEquals(2,s.flags());}assertEquals(1,NetplayGunMailbox.NEUTRAL.flags());assertEquals(3,new NetplayGunMailbox.Sample(0,ZapperInput.pack(0,0,true,true)).flags());}
    @Test void malformedInputsRejected(){var q=new NetplayGunMailbox();assertThrows(IllegalArgumentException.class,()->q.offer(1,1,256,0,0));assertThrows(IllegalArgumentException.class,()->q.offer(1,1,0,240<<8,0));assertThrows(IllegalArgumentException.class,()->q.offer(-1,1,0,0,0));}
    @Test void lockstepSafetyRevisionsOnlyChangeForClearOrOverload(){var s=new LockstepState();s.restart();var id=java.util.UUID.randomUUID();long r=s.releaseRevision();assertTrue(s.acceptInput(id,s.epoch(),0,0,1));assertTrue(s.acceptZapper(id,s.epoch(),0,gun(true),false,false));assertEquals(r,s.releaseRevision());s.clearZapper();assertTrue(s.releaseRevision()>r);var f=s.advanceFrame();assertEquals(1,f.playerOneMask());assertEquals(ZapperInput.NEUTRAL,f.zapperState());r=s.releaseRevision();assertFalse(s.acceptZapper(id,s.epoch()-1,2,0,false,false));assertEquals(r,s.releaseRevision());s.clearController(0);assertEquals(0,s.advanceFrame().playerOneMask());}
    @Test void specialProfileAndHostOwnershipDoNotChangeOrdinaryProfiles(){assertFalse(NetplayProfile.fc().isFcZapper());var p=NetplayProfile.fcZapper();assertTrue(p.isFcZapper());assertEquals(257,p.deviceForPort(0));assertEquals(262,p.deviceForPort(1));assertTrue(NetplayProcess.config(true,true,true).contains("netplay_request_device_p2 = \"true\""));assertTrue(NetplayProcess.config(false,true,true).contains("netplay_start_as_spectator = \"true\""));assertEquals(NetplayProcess.config(false,true),NetplayProcess.config(false,true,false));}
}
